### ISSUE TITLE
disconnect from connection pool before forking still relevant?

### ISSUE THREAD

**Issue by jjb** [puma/puma#1001]
I found this buried in the readme:

> If you're preloading your application and using ActiveRecord, it's recommended that you close any connections to the database here to prevent connection leakage:
>
> ```ruby
> # config/puma.rb
> before_fork do
>   ActiveRecord::Base.connection_pool.disconnect!
> end
> ```

I've never seen this recommendation mentioned in any discussions elsewhere, and the configuration is not included in puma's own heroku plugin https://github.com/puma/puma-heroku/blob/master/lib/puma/plugin/heroku.rb

Is the recommendation still relevant? If so, should it go into the heroku plugin? (I can do a PR)

**Comment by evanphx** [comment]
@jjb It can't hurt to go into the official heroku plugin. @schneems thoughts?

**Comment by schneems** [comment]
Interesting. I guess disconnecting before forking has the same effect as manually connecting after the fork. I prefer that method otherwise if there's a weird race condition where you've done a query in a separate thread or something you might accidentally create another connection maybe?

I don't see adding it as a bad thing, however I also don't entirely think it's necessary. The `establish_connection` should fix any connection pool problems.

Actually, re-read that comment and I think we should be doing it. It's about connection leaks. Right now you might be left with X connections to the database open that you'll never use for each dyno. Not a big deal for a few dynos but if you've got a lot of them connections in PG aren't free. We should probably add it. Can you send a patch to put it in the plugin @jjb ?

**Comment by jjb** [comment]
done!

**Comment by kjvarga** [comment]
Is this still needed under Rails 5.2?  It looks like Rails 5.2 automatically closes connections that were held in other processes.

**Comment by jjb** [comment]
See discussion about rails 5.2 here, in my large unmerged 😭 rails guide https://github.com/rails/rails/pull/29807
