### ISSUE TITLE
DB connection leaks when threads are allowed to spool down

### ISSUE THREAD

**Issue by jjb** [puma/puma#1004]
Long story short:

I was experiencing leaked DB connections in my app. I tried many things, and what finally worked was changing the thread config from `-t 0:8` to `-t 8:8`.

Even with the rails db connection reaper turned on, I was getting the leaked connections with the `0:8` config.

In my case there is no benefit in going back to the previous config, so I don't think I'll be able to spend the time to come up with a minimal app demonstrating the problem. But I just wanted to mention it in case it was useful or interesting.

**Comment by jrafanie** [comment]
@jjb I don't think activerecord's reaper does what you are expecting.  It reaps connections [reserved for threads back into the connection pool for general use](https://github.com/rails/rails/blob/578f2c87d004a0afb1a2fc74c25dc457288c41ac/activerecord/test/cases/reaper_test.rb#L61-L82).  Unless you're doing absolutely nothing, I've found that the database.yml pool size is the number of db connections you'll see in pool.  ActiveRecord eagerly passes out connections until the pool size is reached and keeps those connections alive even if they aren't reserved by threads for a long time.  

I would not expect spinning down the number of puma threads to decrease the number of connections in your pool unless you also change the pool size in database.yml.  I also don't know if you can dynamically lower the size of the connection pool and see those connections be disconnected.

**Comment by jjb** [comment]
@jrafanie thank you for your thoughts and info!

To clarify: I was not trying to spin down threads in order to release db connections. I was noticing that I was leaking connections, and when I stopped allowing threads to spin down, the problem was fixed.

So my vague suspicion is that the threads "aren't really" being spun down, so AR is still holding onto them. Meanwhile, new ones are spun up. Eventually, there are no more available connections in the pool because the old, unused threads are holding onto them all and not doing anything with them.

**Comment by jrafanie** [comment]
@jjb if it's helpful, you could take something [like this for Rails 5](https://github.com/ManageIQ/manageiq/pull/8275) to log the checkout/checkin of connections from the pool.  I believe one or two of the attributes of the pool are different in Rails 4, maybe num_waiting_in_queue, I don't remember.  If your logger logs Process id and thread id, you can easily see when the pool grows, connections are checked out and checked back in.  I don't know if the repear has callbacks you can hook for logging.  I don't know that it's puma at all.  

One pain point is that any rails rack request to puma needs to checkout a connection as part of the [query cache middleware](https://github.com/rails/rails/blob/578f2c87d004a0afb1a2fc74c25dc457288c41ac/activerecord/lib/active_record/query_cache.rb#L27) and because puma uses threads, you have thread contention on the pool so you have to make sure you don't have threads constantly in `waiting_in_queue` as per my link above for logging the pool information.  To do this, you have to have pool size greater than the number of puma threads handling rack requests.  This was a big pain in development mode where my rails server is processing requests for assets.  😢 

Good luck!

**Comment by gjastrab** [comment]
@jjb [here is a Rails 4 version](https://gist.github.com/gjastrab/53410eee6827cf1b44426bd95cf12019) of what @jrafanie suggested above.

This was intermittently happening for us as well, and I realized that our connection pool settings in `config/database.yml` were quite close to the threshold, but even after bumping the pool size higher this is still happening for us.

Relevant sections of our puma config is:

```
workers 2
threads 0,6
prune_bundler
```

So we are in clustered mode without preloading so we can do rolling updates.

I just added the connection pool logging yesterday and bumped up our threads to be `threads 6,6` as suggested in this issue and it does seem to have helped so far.

Other relevant version info for us:
* Ruby 2.2.4
* Rails 4.1.6
* Puma 3.4.0
* Sidekiq 3.4.1

In this staging environment our pool size was bumped up to 22 (from the previous value of 18) so that there is more overhead above the `2 * 6 + 3` (3 comes from us starting Sidekiq with a concurrency setting of 3).

Also I just want to confirm since we are not pre-loading our app we should not have to do any special `on_worker_boot` or `before_fork` blocks due to are using `prune_bundler` right?

I had asked this [in the puma gitter.im](https://gitter.im/puma/puma?at=57222bdb11317a7d27a7d978) a few weeks back as well. @jjb when you notice the leaking happening would you see the workers logging `! Detected parent died, dying` ?

At some point when this happens the workers would still be running and if we curl the stats from the local control app we would see something like this for the last_status of each worker:

```
"last_status": { "backlog":124, "running":0 }
                            ^
                              \ this number will continue to climb until QUIT'ing puma and starting back up
```

**Comment by jjb** [comment]
@jrafanie @gjastrab thanks for your info. at this point my problem is completely solved by pinning the thread number, so I won't be able to invest any time in exploring this in the near future. 

> so that there is more overhead above the `2 * 6 + 3`

you have your math wrong, the pool is per-puma-worker and per-sidekiq-instance. so for rails, the pool should be 6 or more and for sidekiq the pool should be 3 or more.

> when you notice the leaking happening would you see the workers logging `! Detected parent died, dying` ?

no, this was never in my logs

**Comment by gjastrab** [comment]
@jjb cool watching our server all day today too the issue seems to have been corrected by pinning the thread together as well. Still seems like there's a bug here though right?

Ah pool per worker makes sense I think I had meant to confirm that here at some point but forgot to come back to it. Will try turning those down and ensure everything is still smooth.

**Comment by jrafanie** [comment]
Are you saying the number of connections to the database exceeds the connection pool size?

Could you share what information you're finding on the system during a "normal" spun up state vs spun down? Number of threads in puma, number of connections from that process as reported by the database, connection pool size, number reserved, number waiting, etc.

**Comment by jjb** [comment]
@jrafanie are you addressing me, @gjastrab, or either? :)

**Comment by jjb** [comment]
In my case, if I allow threads to go up and down, then I eventually always get the "active record can't find an available db connection in the pool" error. this is regardless of pool size. typical config is 16 threads, 20 db connection pool size.

**Comment by evanphx** [comment]
The thread pool of your database needs to be at least as long as the number of threads puma is configured to use. Additionally, you need to be sure that the connections are returned to the pool when a request finishes (rails handles that for you but older versions have had bugs where connections were not returned).

Also consider turning on `clean_thread_locals` in your puma config, that can help because it will make sure that Thread locals (where database connections are sometimes stored) are properly cleaned up.

**Comment by jjb** [comment]
>The thread pool of your database needs to be at least as long as the number of threads puma is configured to use. Additionally, you need to be sure that the connections are returned to the pool when a request finishes (rails handles that for you but older versions have had bugs where connections were not returned).

Both of these things were the case when I was experiencing the problem.


> Also consider turning on clean_thread_locals in your puma config, that can help because it will make sure that Thread locals (where database connections are sometimes stored) are properly cleaned up.

I'd never heard of this, I'll try it next time I have the problem. Seems very magical and useful! How long has it been around?

**Comment by evanphx** [comment]
@jjb It's been around a while. At some point I'll probably make it the default even though it has a minor performance implication.
