### ISSUE TITLE
Puma won't daemonize when using Jruby and JMX port in JRUBY_OPTS

### ISSUE THREAD

**Issue by cevans111** [puma/puma#1035]
I get the following error when trying to run as a daemon when using Ruby running Puma 2.15.3

```
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9010; nested exception is:
	java.net.BindException: Address already in use
! Error starting new process as daemon, exiting
```

I have the following environment variables set:

```
JRUBY_OPTS=-"J-Xmx1024m -J-Dcom.sun.management.jmxremote \
-J-Dcom.sun.management.jmxremote.port=9010 \
-J-Dcom.sun.management.jmxremote.local.only=false  \
-J-Dcom.sun.management.jmxremote.authenticate=false \
-J-Dcom.sun.management.jmxremote.ssl=false "
```
I'm guessing that this is because the parent process is holding onto the jmxremote port while starting up the daemon process?

This works fine without the -d flag.

**Comment by cevans111** [comment]
More detail, after finding a similar issue, this is my startup command:
`jruby -S pumactl -S puma.state start -d`

It looks like pumactl is holding the jmxremote port

**Comment by evanphx** [comment]
Yeah, so Puma has a work around for this issue. Basically demonization in jruby is really hard because the JVM works very hard to make it difficult. Puma allows it use some funky exec techniques. These techniques cause the issues you're seeing though.

So, to get around this, use the env var `PUMA_JRUBY_DAEMON_OPTS` instead of `JRUBY_OPTS`. Puma will detect that env var and move the options to `JRUBY_OPTS` in the final process only, making the JVM happy.
