### ISSUE TITLE
Debugging signal handler

### ISSUE THREAD

**Issue by mperham** [puma/puma#1041]
I'd like to see a signal handler that reports all backtraces in the puma process.  This can be very helpful when debugging stuck processes.  Sidekiq uses the TTIN signal for this purpose, "gimme **T**hat **T**hread **IN**fo".

https://github.com/mperham/sidekiq/wiki/Signals#ttin

**Comment by mperham** [comment]
Here's the impl:

```ruby
      when 'TTIN'
        Thread.list.each do |thread|
          Sidekiq.logger.warn "Thread TID-#{thread.object_id.to_s(36)} #{thread['label']}"
          if thread.backtrace
            Sidekiq.logger.warn thread.backtrace.join("\n")
          else
            Sidekiq.logger.warn "<no backtrace available>"
          end
        end
      end
```

**Comment by rosenfeld** [comment]
:+1:  My Puma process got stuck today once again (it only happens in development mode so far, so I suspect it's related to some auto-reloading code I have) and it would be very helpful if I could get a dump for all threads. Unfortunately I can't get this backtrace by attaching gdb to the process because MRI doesn't allow me to inspect Ruby backtraces for threads not own by gdb or something like that. I'm planning to implementing this by using some custom code around the 'listen' gem by watching some file, but I agree with @mperham that a signal supported by Puma would be best as it would allow me to inspect any Puma process without any custom instrumentation set by me previously... I was about to create the same request when I saw @mperham have already created one.

**Comment by nateberkopec** [comment]
I'm not sure what signal we could use. SIGINFO feels natural, but Linux doesn't have it.
