### ISSUE TITLE
Forwarding interrupted requests

### ISSUE THREAD

**Issue by janko** [puma/puma#1067]
First of all, thank you for all your hard work on Puma, and for the latest 3.x releases! ❤️ 

I have a requirement that I was wondering if Puma can satisfy. I'm implementing [tus](http://tus.io/), the resumable upload protocol on top of HTTP. One part of specification is this:

> The Server SHOULD always attempt to store as much of the received data as possible.

Basically, this means that, if the client is uploading the file, and the request gets interrupted (e.g. due to a connection hiccup or tab close), the server should attempt to store all the data (request body) that it has received up until that point.

I was wondering if it's possible to configure Puma to still forward the request to the Rack app if the request was interrupted/closed. Of course, all request headers would still need to be received, but not the whole request body.

**Comment by janko-m** [comment]
The previous server implementation for the "tus" protocol used [Goliath](https://github.com/postrank-labs/goliath), which allows this by leveraging EventMachine. This is the only blocker in making my Rack implementation fully equivalent to the Goliath/EventMachine one.

**Comment by evanphx** [comment]
Hi @janko-m,

There are 2 fixes to make this work, one long term, one short term:

Short term: An option that will control passing the body even if the connection was closed while reading it. I'm totally open to this and it would fix your use case.

Longer term: Make the request body into a streaming reader so that it's not read at all until you start doing so, which will mean you'll be able to implement your logic on what to do. This is a bit of work and it's a little confusing for users because they're not expecting the `#read` from the body to return an IOError.

I'm happy to implement the short term one now, are you fine with that?

**Comment by janko-m** [comment]
The short term solution sounds perfect. Thanks, @evanphx!
