### ISSUE TITLE
#processes vs. #threads

### ISSUE THREAD

**Issue by ce07c3** [puma/puma#1116]
Our Puma instance is receiving a lot of fast requests. No matter how much we scale Heroku, we always have a queue time per request of around 100ms. When we use too many threads, Puma can die seemingly at random and not recover - maybe because it gets stuck?

On New Relic I am furthermore seeing this:

<img width="992" alt="screen shot 2016-10-20 at 00 48 26" src="https://cloud.githubusercontent.com/assets/6344545/19540374/4d6dac06-965f-11e6-8f09-86be3a3d4a92.png">

Any idea what this could mean? Why would so many calls be spent there?

**Comment by evanphx** [comment]
The code in the ThreadPool that's sleeping is just the autotrim functionality. It checks the size of the pool at a fixed interval of seconds to see if it should be sized down, so it doesn't indicate a problem with performance at all.

The code blocking in connection_pool usually indicates that the size of your connection pool doesn't match the size of the thread pool. Those should be matched otherwise threads will wait for a connection (which is what you're seeing here).

**Comment by ce07c3** [comment]
Thanks, @evanphx. My min size of threads equals my max size of threads as per Heroku's recommendation, as do the number of connections. I guess all is fine and Ruby 2.3.1 just has an insatiable appetite for memory.
