### ISSUE TITLE
Setting no_token option causes crash

### ISSUE THREAD

**Issue by jlarigakis** [puma/puma#1193]
### Steps to reproduce

1) Put `{ no_token: true } ` as an option to `activate_control_app` in `puma/config.rb`, for example:
`activate_control_app 'unix:///tmp/pumactl.sock', { no_token: true }`

2) Attempt to start the server with
`pumactl start`

### Expected behavior

Puma should start

### Actual behavior

Puma crashes with the message ```undefined method `rindex' for :none:Symbol```

### System configuration

**Ruby version**: 2.4.0
**Puma version**: 3.6.2

## Notes

This issue can be worked around by using `{ auth_token: '' }`, however the example file suggests the `no_token` syntax, which is broken.

**Comment by manishval** [comment]
@nateberkopec I have started looking at this and it seems to be an issue with `OptionParser` parsing the `:none` value  [being set](https://github.com/puma/puma/blob/992fd0d26fd2111b086da23a0bd6cbcdc9442fc4/lib/puma/dsl.rb#L96) for `control_auth_token`. `OptionsParser` is expecting a string instead of a symbol.

I'm not sure what the intended behavior should be in terms of the `no_token: true` option and the `control_auth_token`. But it looks like we can set the value of `control_auth_token` to an empty string instead of `:none` and it will be taken care of in the [runner](https://github.com/puma/puma/blob/master/lib/puma/runner.rb#L49).

**Comment by nateberkopec** [comment]
@manishval Sounds like you're most of the way there. Open a PR?
