### ISSUE TITLE
Rails 2 support

### ISSUE THREAD

**Issue by drnic** [puma/puma#12]

**Comment by Hareramrai** [comment]
Hi there,
I am trying to update the our application server to use puma from unicorn. I am using Rails 2.3.18 & Ruby 1.9.3. I have followed all steps given in https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server . But I got the bellow error in our server log.

````
foreman start -p 3000
15:10:55 web.1            | started with pid 5395
15:10:55 worker.1         | started with pid 5397
15:10:55 monitor_daemon.1 | started with pid 5400
15:10:58 web.1            | [5399] Puma starting in cluster mode...
15:10:58 web.1            | [5399] * Version 2.11.3 (ruby 1.9.3-p484), codename: Intrepid Squirrel
15:10:58 web.1            | [5399] * Min threads: 1, max threads: 1
15:10:58 web.1            | [5399] * Environment: development
15:10:58 web.1            | [5399] * Process workers: 3
15:10:58 web.1            | [5399] * Preloading application
15:10:58 web.1            | [5399] ERROR: No application configured, nothing to run
15:10:58 web.1            | exited with code 1
15:10:58 system           | sending SIGTERM to all processes
15:10:58 worker.1         | terminated by SIGTERM
15:10:58 monitor_daemon.1 | terminated by SIGTERM
````
Please help me on this.
Thanks,
Hare

**Comment by hron84** [comment]
@Hareramrai you just missed a very important point of the documentation.
The documentation says the following:

> This should point at your applications config.ru, which is automatically generated by Rails when you create a new project.

There is a problem with the second part of the sentence, since Rails 2.3.x does **not** generate config.ru automatically, you have to write one for yourself.

I recommend you to read [this](http://stackoverflow.com/a/17827344/182474) thread on StackOverflow about the topic, both the opening post and the linked solution too.
