### ISSUE TITLE
Sinatra support

### ISSUE THREAD

**Issue by drnic** [puma/puma#13]
README additions

**Comment by 9mm** [comment]
@guilhermesimoes  did you ever figure out how to set config options? I've been trying to do this for ages and can't figure it out...

**Comment by nateberkopec** [comment]
You should be using `bundle exec puma`, not `bundle exec rackup`.

**Comment by 9mm** [comment]
To anyone that found this thread I solved it here:

https://stackoverflow.com/questions/45195708/how-to-pass-config-file-to-puma-sinatra

**Comment by nateberkopec** [comment]
You can run your Sinatra application with Puma from the command line like this:

```
$ ruby app.rb -s Puma
```

In order to actually configure Puma using a config file, like `puma.rb`, however, you need to use the `puma` executable. To do this, you must add a rackup file to your Sinatra app:

```ruby
# config.ru
require './app'
run Sinatra::Application
```

You can then start your application using:

```
$ bundle exec puma 
```
