### ISSUE TITLE
Native Websocket Support

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1316]
See previous attempts at #1054 #1056

**Comment by Jesus** [comment]
Hi,

Soon I'll be attending a coder's retreat for 3 months, this means I'll have a lot of time to make open-source contributions. I've set myself the goal to implement this feature. I believe it'd be great to have it and eventually update https://github.com/rack/rack/pull/1272.

For now, my plan is to get started getting familiar with the code base by helping you closing some tickets. Perhaps you have something you'd like someone else to take care of? Or maybe something that should be done before tackling this one directly?

I understand all contributors to this project do it in their spare time so I don't expect to be mentored, just wanted to share my plans with you in case you wanted to give me some tips. It's ok if you can't respond.

Also, thanks for the awesome work!

**Comment by nateberkopec** [comment]
Hey @evanphx where do you think we stand on this feature after the nio4r reactor was merged?

**Comment by Jesus** [comment]
I'm not sure if it'll be a waste of time but I'll spend the day of tomorrow trying to recover #1054. Perhaps: rebasing, adding tests to it and eventually trying it with a basic chat application.

**Comment by nateberkopec** [comment]
#1849 linking. This is a good implementation start. 

This issue is open for anyone take up.

**Comment by Mai-Lapyst** [comment]
What is the current status of this feature?

If no one currently works on this, I am willing to help.

**Comment by nateberkopec** [comment]
@Mai-Lapyst No one has taken this on - join us in the Matrix channel (see CONTRIBUTING.md for link) and let's discuss

**Comment by Mai-Lapyst** [comment]
Thanks for the invitation ^^ will setup matrix in the comming days.

In the meantime: ive looked around and it seems that #1849 is the most promising; especaliy because it seems to me that the only blocker for it was that the original author had no time working on it anymore.
For now I will start rebasing #1849 against the current master and do some testing with it.

**Comment by Mai-Lapyst** [comment]
I've worked on this the last weeks and found out that the old pr cannot be merged since the code changed to much since then, for example the reactor.

So i've simply used the old pr to read and written the code new into the current structure of puma, and also opened a draft pr with the code: https://github.com/puma/puma/pull/2646.

**Comment by dentarg** [comment]
I think this was finally addressed with https://github.com/puma/puma/pull/3058

Please correct me if I'm wrong!
