### ISSUE TITLE
Missing gem dependency on puma restart

### ISSUE THREAD

**Issue by esparkman** [puma/puma#1547]
### Steps to reproduce

1) Start puma with puma --control 'tcp://127.0.0.1:9293' --control-token foo -C config/puma.rb

2) Restart puma with pumactl -P tmp/pids/puma.pid -C 'tcp://127.0.0.1:9293' -T foo restart

3) ...

### Expected behavior
I would expect the puma processes to be restarted.

### Actual behavior

[86083] - Gracefully shutting down workers...
[86083] * Restarting...
Could not find CFPropertyList-2.3.6 in any of the sources
Run `bundle install` to install missing gems.

### System configuration

**Ruby version**: 2.3.6p384
**Rails version**: 3.2.22.5
**Puma version**: 3.11.3

**Comment by esparkman** [comment]
CFPropertyList seems to be a dependency on the fog gem. I'm not sure why issuing the restart command would fail to load dependencies. Thoughts?

**Comment by nateberkopec** [comment]
Can you confirm that starting a basic app with just the fog gem in the Gemfile reproduces the error?

**Comment by DangerDawson** [comment]
@esparkman did you managed to solve this? I am seeing this behaviour.

If I downgrade to 3.8.1 the problem ceases to exist

**Comment by DangerDawson** [comment]
@esparkman the issue for me was being caused by the following:

I installed `tmuxinator` using bundler for a different gemset
When I then started puma using `tmuxinator` it was picking up `Bundler::ORIGINAL_ENV` from my previous environment, so when puma restarted it was looking for gems from the gemset that `tmuxinator` was installed under.

Does the above make sense?
