### ISSUE TITLE
Puma is using MiniSSL. What is the difference between MiniSSL and OpenSSL?

### ISSUE THREAD

**Issue by BlackNightFury** [puma/puma#1561]
Hi. I am using the Puma.

But I can see that Puma is using MiniSSL and it hasn't some functionalities which OpenSSL has.

Why is Puma using MiniSSL?

**Comment by perlun** [comment]
@BlackNightFury MiniSSL is not a concept in itself, more than the class name of Puma's SSL implementation which can be found here: https://github.com/puma/puma/blob/master/lib/puma/minissl.rb

I don't have much experience with it myself, but is currently looking into start using it for development & production usage. To the best of my knowledge "it works" (even though I've seen some exceptions & weird behavior; will file issues about them if I can reproduce it.)

What are the _specific_ things in "OpenSSL" (a C library used for implementing SSL/TLS support) that are missing in Puma? If you make a list and be very specific, I am sure you will get more feedback from the project maintainers. (I am not a maintainer myself.)

**Comment by BlackNightFury** [comment]
@perlun Thanks for your response.

So we have been using OpenSSL and our project needs strong security.
We planned to move from thin to puma because of concurrency issue but we also could see that Puma is using MiniSSL not OpenSSL.

So can you guarantee that MiniSSL is same as OpenSSL?

**Comment by perlun** [comment]
@BlackNightFury 

> So we have been using OpenSSL and our project needs strong security.

Please define "strong security".

> We planned to move from thin to puma because of concurrency issue but we also could see that Puma is using MiniSSL not OpenSSL.
> 
> So can you guarantee that MiniSSL is same as OpenSSL?

I can most certainly guarantee that MiniSSL is _not_ the same as OpenSSL. [OpenSSL](https://www.openssl.org/) is a library which implements the SSL/TLS protocols. [LibreSSL](http://www.libressl.org/) is another library which was forked from OpenSSL a few years ago.

Can you guarantee that LibreSSL is the same as OpenSSL? Probably mostly yes, since they share the same ancestry, but there might still be subtle differences.

Can you guarantee that Puma's MiniSSL implementation is the same as OpenSSL? No, it's a different implementation of its own.

I guess what you're really asking is whether Puma's MiniSSL imlpementation is _secure enough_. To that, I cannot really answer - @evanphx or @nateberkopec are probably much better suited to answer that. (I would also be personally interested in the answer btw 😄)

**Comment by BlackNightFury** [comment]
@perlun Thanks for your answers.
Then how can I define certificate stores using MiniSSL? OpenSSL provides OpenSSL::X509::Store.

But I couldn't find this one.

**Comment by perlun** [comment]
@BlackNightFury I think if you share some code example of what you are trying to achieve, it will be easier for me or others to help you. What are you doing _more specifically_ with `OpenSSL::X509::Store`?

(I am currently using Puma with SSL, it seems to work pretty fine - great on MRI, almost great on JRuby.)

**Comment by MSP-Greg** [comment]
@BlackNightFury

Both [Ruby OpenSSL](https://github.com/ruby/ruby/tree/trunk/ext/openssl) and [Puma MiniSSL](https://github.com/puma/puma/blob/master/ext/puma_http11/mini_ssl.c) are compiled using the [OpenSSL library](https://www.openssl.org/).

As to how to use MiniSSL, I would suggest reviewing code in the [Puma tests](https://github.com/puma/puma/tree/master/test).

Greg
