### ISSUE TITLE
Puma not raise error when set non-existing pidfile folder path

### ISSUE THREAD

**Issue by r3cha** [puma/puma#1641]
I have simple puma config 
```
threads 0, 2

port        ENV.fetch("PORT") { 3000 }
environment 'development'
workers ENV.fetch("WEB_CONCURRENCY") { 2 }
preload_app!
daemonize true
pidfile './tmp/pids/puma.pid'
plugin :tmp_restart
```
I don't have `./tmp/pids` folder in my project and run `pumactl start`
I have seen normal behavior:  
![screen shot 2018-08-29 at 2 46 42 pm](https://user-images.githubusercontent.com/8098344/44785679-64d82400-ab9a-11e8-9d26-faa6c2b08ad6.png)
But application not started and haven't process on 3000 port
Then I found that have no  `./tmp/pids/` folder
I check [line](https://github.com/puma/puma/blob/5a7d884bdc300f477d0559181af1d52f37eaa4d3/lib/puma/launcher.rb#L131) that write pid in file and repeat it in irb... try open folder and write pid to file 
everything looks good:  
![screen shot 2018-08-29 at 2 49 35 pm](https://user-images.githubusercontent.com/8098344/44785834-e5972000-ab9a-11e8-8f2a-76b947206856.png)
But this error not rising in pumactl when I set in config/puma.rb non-existing folder like: 
`pidfile './tmp/pids222/puma.pid'`

**Comment by Jesus** [comment]
I think it's behaving as expected. Otherwise, what would be the expected behavior?

The stack trace is swallowed because the pidfile is created after the process is daemonized, it's impossible to do it before as we don't know the PID yet.

It would be possible to check that the file is writable before daemonizing, but that'd just capture one of many errors that may arise after the process is forked.

Another approach would be to monitor the forked process for a few seconds and give the terminal back to the user only when puma has booted correctly, instead of immediately after being daemonized. But this is a whole new feature that I'm unsure you'd want to support.

**Comment by harmdewit** [comment]
Might be interesting to know that when using rails the `tmp/pids` file is automatically created when starting the server with `bundle exec rails server puma`, see https://guides.rubyonrails.org/initialization.html#rails-server-start

This file isn't automatically created when starting the server via `bundle exec puma`, which is expected because puma does not enforce the folder structure. 

It is inconvenient though that both commands work differently. In Rails 6 the `pidfile` is enabled by default while the `tmp/pids` folder is gitignored, which easily results in this error after a git clone (CI, deployments).

**Comment by nateberkopec** [comment]
Hm, so now that daemonization is gone, I agree that this isn't Puma's problem.

**Comment by julianammann** [comment]
> FYI: in Rails the `tmp/pids` folder is automatically created when starting the server with `bundle exec rails server puma`, see https://guides.rubyonrails.org/initialization.html#rails-server-start
> 
> The folder is not automatically created when starting the server via `bundle exec puma`, which is expected because puma does not enforce the folder structure.
> 
> It is inconvenient though that both commands work differently. In Rails 6 the `pidfile` is enabled by default while the `tmp/pids` folder is gitignored, which easily results in this error after a git clone (CI, deployments).

The correct command is nowadays ```bundle exec rails server -u puma```
