### ISSUE TITLE
Poor performance for vertical scaling

### ISSUE THREAD

**Issue by collimarco** [puma/puma#1734]
### Steps to reproduce

1.  Create a bare new Rails 5 application with Puma and use a standard configuration (e.g. 2 workers, 5 threads, 1024 backlog)
2. Add a static page (only a view with some lines of html) which doesn't make database calls
3. Start a standard 1x dyno on Heroku
4. Run a test with the loader.io addon and you get about 300rps, which is good
5. If you try horizontal scaling everything also works as expected: for example with 20 dynos (standard 1x) you get about 6000rps, which is good (only the start is slow, probably due to the way cpu is allocated)
6. However vertical scaling doesn't work: try to replace a 1x standard dyno ($25) with a performance M dyno ($250) and you get pretty much the same results, without any improvement
7. Try to increase the number of Puma workers from 2 to 4 and you still get the same results... if you try to further increase workers (e.g. up to 10) you get even worse results

### Expected behavior

I expect that Puma can serve 10 times more requests on a server that costs 10 times and has 10 times the computing power compared to another server.

### Actual behavior

It seems that Puma cannot scale well vertically and that there are some bottlenecks that prevent Puma from using many workers efficiently.

### System configuration

**Ruby version**: 2.5.3
**Rails version**: 5.2
**Puma version**: 3.12

**Comment by nateberkopec** [comment]
Standard 1x dynos and performance-M dynos have roughly the same logical cores available (2).

Try Perf-L with ~8-12 Puma workers.

**Comment by nateberkopec** [comment]
> I expect that Puma can serve 10 times more requests on a server that costs 10 times and has 10 times the computing power compared to another server.

This is more of a problem with the way Heroku explains and prices their dyno types than Puma. What matters for vertical scaling is the total number of logical cores. Perf-M and Standard dynos have access to (roughly) the same number.

**Comment by collimarco** [comment]
This is the result that I get with performance L for a simple html page (without db):

- https://ldr.io/2VITU8t (4 workers, max ~900req/s)
- https://ldr.io/2UpRqvA (8 workers, max ~1500req/s)
- https://ldr.io/2Uofpet (12 workers, max ~1500req/s)

I can see an improvement from 4 workers to 8 but then it stops. So the max that I can get is 1500req/s. 

Basically:

- running 20 instances of 1x standard dynos (tot $500) produces ~6000req/s 
- running 1 instance of performance L dynos (tot $500) produces ~1500req/s

It's either Heroku pricing that is wrong or Puma that scales better horizontally than vertically.

**Comment by nathansamson** [comment]
Where is it documented that performance l dynos have 12 threads?

**Comment by collimarco** [comment]
@nathansamson I was talking about Puma worker processes (e.g. 12 workers with 5 threads each). More about dyno types: https://devcenter.heroku.com/articles/dyno-types

**Comment by nateberkopec** [comment]
Heroku Perf dyno pricing is definitely wonky, you don't have to run a benchmark to see that. Perf-M dynos have 1/4 of the CPU threads and 1/6 the memory of Perf-L dynos, but cost 1/2 as much, for example. 

Your benchmark sounds very I/O light and CPU-heavy. That's why you're not seeing better results once you add more processes beyond the amount of hyperthreads available (8 on a Perf-L).

Sounds like you're just seeing the underlying economics of the Heroku platform. Otherwise everything about your benchmark results are as expected. Note also that Standard dynos technically "share" 8 cores with whoever else is on your dyno. I don't exactly know how the Heroku hypervisor works but it's entirely possible you could have access to 8 hyperthreads at once, the same as you get on Perf-L (you just get reduced "time" on them), which could be why standard dynos are performing well here.

Happy to continue to discuss this over email but I'm going to close as there's no issue with Puma here.
