### ISSUE TITLE
Precompiled windows binary

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1792]
As requested by @MSP-Greg 

Would this improve the dev experience for a first-timer working on a Rails app on Windows?

**Comment by MSP-Greg** [comment]
I suspect that most of the people watching are not Windows users, let alone 'first-timers'.  Most windows users are (hopefully) using Ruby 2.4 or later, which is much easier to build with.  Ruby 2.4 is built with OpenSSL 1.0.2, 2.5 and later are using 1.1.1.

The Appveyor build/test system allows Windows users to easily download a pre-compiled gem built on master if they need to test something...

**Comment by MSP-Greg** [comment]
I don't recall seeing anyone mentioning the issue here, but in one of the popular database connector/adapter gems, the issue was raised over the additional time to spin up a Windows server when the MSYS2 build system needs to be installed to build an extension gem.

Pre-built exe files of Windows Ruby builds are available, the plain Ruby exe is about 10 MB, the exe that includes the MSYS2 build system is 126 MB.  Along with the larger download, it takes a some time to unzip the larger one.

Obviously, Windows cloud apps running Puma are probably uncommon...

**Comment by dentarg** [comment]
Are we still interested in this? Demand doesn't seem to be huge :-)

**Comment by MSP-Greg** [comment]
> Demand doesn't seem to be huge :-)

If Puma was included in what could be considered a 'desktop' app, like Jekyll, a pre-compiled gem might be a good idea.  Since it's really a 'server' app/gem...

Closing...
