### ISSUE TITLE
Documentation Around Setting Puma Environment

### ISSUE THREAD

**Issue by dlinch** [puma/puma#1795]
### Steps to reproduce

1) Puma docs don't really specify why we need to set the Environment in the puma config.

### Expected behavior
In the environment section of the documentation, it basically says "set environment here."

### Actual behavior
 I would expect the documentation to explain a little more the impact that setting environment has.

### System configuration
N/A

### Context
We recently ran into an issue where we discovered that we weren't properly setting RACK_ENV in our production environment, so our Puma servers were being booted with "development" environment. I went to investigate what impact this might be having, and all I could find in reference to the environment was that it uses that environment configuration to look for where to find its configuration file. This is also a little confusing, as you can set the environment inside the config file, but if it's only using the environment to reconcile the location of the config file, which it must have found already to be reading from, I'm not sure it's actually even doing anything (unless there are undocumented speed side effects, hence this issue). *EDIT* I realized that it might be using that environment to find a config to override defaults.

We're loading puma with the -C option, so that it wasn't really affecting us, but I couldn't find any other documentation explaining if there were any performance enhancements or side effects by running Puma in "production" versus "development".

I would open an PR to add to the ReadMe that the environment is only used to help Puma locate the appropriate config files, but I don't actually know that for sure.

**Comment by nateberkopec** [comment]
You're right. We should document any environment variables Puma reads, and what they do.

Here's the ones I can find:

`DISABLE_SSL`
Environment config loading (/config/puma/`RACK_ENV`.rb)
`SCRIPT_NAME`
`LISTEN_PID`
`BUNDLE_GEMFILE`
`RACK_ENV`
`PUMA_DEBUG`
`PUMA_BUNDLER_PRUNED`
`PUMA_JRUBY_DAEMON_OPTS`
`PUMA_INHERIT`
`PWD`

**Comment by an-gril** [comment]
You need to do a bit more than that! 
Where is the config file found? for one.
In reality, I am unable to get started because the examples use a $ prompt without explaining in what context that prompt occurs. Is it a Bash shell? or something to do with Gem or Ruby or Rails? (I am using OpenBSD, so my default shell is Ksh). But before the commands you show will work, I would guess some stuff has to be installed. What? Does any of it need to be started? If so, how? (Generically, not one specific example).

**Comment by nateberkopec** [comment]
Thanks for your input @an-gril. Since puma was included in the default Rails gemfile a few years ago we've had a lot more traffic on this repository from more "beginners" (or people new to the Ruby web ecosystem), and I think our documentation could certainly improve to suit that.

**Comment by Jesus** [comment]
>I would open an PR to add to the ReadMe that the environment is only used to help Puma locate the appropriate config files, but I don't actually know that for sure.

Hi @dlinch here're my findings if you still want to send that PR.

After a bit of research, I believe that the environment has only three side-effects:
 1. Find configuration file as you described.
 2. Stack traces are shown on development & test (https://github.com/puma/puma/blob/v4.0.0/lib/puma/runner.rb#L177-L179)
 3. Puma will set RACK_ENV so all middleware on top of it may also change its behavior.

Also, apart from setting RACK_ENV, Puma may use RACK_ENV to set its environment if it's been previously defined (https://github.com/puma/puma/blob/12d1706ddc71b89ed2ee26275e31c788e94ff541/lib/puma/configuration.rb#L185).

I hope this clarifies enough to update the documentation, otherwise please send me your questions.

I'll research the other environment settings for a different PR.
