### ISSUE TITLE
#1189 was closing 'in my face' - just wanted to tie it all together :(

### ISSUE THREAD

**Issue by wdiechmann** [puma/puma#1807]
This comment really belongs to issue #1189 - but that one was "closed smack in my face" (and possibly for good reasons) so even though I worked feverishly through the night I didn't make it 'til closing time :(

My purgatory setting up NGiNX proxying Puma in a Rails5 ActionCable project albeit met with a happy ending - eventually :)

I've committed all the changes to the https://github.com/wdiechmann/sucker demo project.

Please allow me to excuse to anybody who is left feeling insulted by my brash style!

The gist of it was: when I started from the top, built a fresh CentOS virtual machine, and disabled SELinux, suddenly everything was dandy!

(I sure would have loved to point a finger at that 'WebSocket closed before...' message in my DevTools console, but that will have to be another time)

cheers,
Walther

**Comment by wdiechmann** [comment]
done :)

**Comment by nateberkopec** [comment]
I've started locking issues that may be placing well in Google results or are otherwise prone to necromancy. We have a very limited amount of resources to maintain Puma and it's extremely widely used, so I have to be a little merciless with issue triage (as I am the only one able to do that!). Not your fault and you've done nothing really wrong.

**Comment by wdiechmann** [comment]
Good to know :)

- and I should have emptied my options prior to jumping the gun (looking in the rear mirror)

Cheers
Walther
