### ISSUE TITLE
Persistent Connections monopolize a thread

### ISSUE THREAD

**Issue by twalpole** [puma/puma#1835]

**Comment by nateberkopec** [comment]
Linking #1565 on a hunch

**Comment by twalpole** [comment]
@nateberkopec From a quick read of the issue you linked I don't believe they're the same issue - but I could be wrong on that.

**Comment by Jesus** [comment]
I've been debugging this. I don't have a fix yet but I have some findings.

This is because the MiniSSL implementation of `#read_nonblock` blocks here:

https://github.com/puma/puma/blob/099a4476a3e27dce83d63e890e3150d05666ef2f/lib/puma/minissl.rb#L60-L66

This is particularly bad because the method is being called from inside the thread pool, which as the OP accurately reports monopolices the thread. At least this only happens when using SSL.

I'm tempted to update that piece of code so it'll raise `Errno::EAGAIN` instead of blocking. Doing that fixes the issue.

But I want to understand better the reasoning that lead to the current behaviour.

**Comment by nateberkopec** [comment]
Linking @Jesus's comment on #1439 https://github.com/puma/puma/pull/1439#discussion_r305146632

**Comment by MSP-Greg** [comment]
I ran up essentially 4.0.1 with -t 1:1 locally, then ran both Chrome & Firefox, and both were responsive.  Couldn't find the info in Firefox, but Chrome was connected via TLSv1.3.  Interesting. I look more later...

**Comment by Jesus** [comment]
That's weird, I could reproduce the issue easily using the gist above.

I'll try to write a test in #1857 to catch this.

**Comment by ezekg** [comment]
I believe I'm seeing this behavior as well on Puma 4.0.1, Rails 5.2, Ruby 2.6. I did load tests with and without keep-alives, respectively, to try and figure out why my active thread count was so high even though request volume had returned to normal after a quick spike.

When using keep-alives, it looks like Puma maintains idle threads that can't be used by other requests, which greatly reduces throughput until those sockets time out.

![image](https://user-images.githubusercontent.com/6979737/61568838-8b20df80-aa4a-11e9-8657-154a65e5778c.png)

Another question I have is why a good portion of these idle sockets/threads never timed out (as you can see from the chart — some stayed around for almost an hour requiring a forced restart of all dynos), even though my `persistent_timeout` is set to `30`.

When forcefully restarting the dynos, I also saw some R12 errors, which means the process didn't exit within 10s, but that may be unrelated (I had never seen an R12 before today).

**Comment by nateberkopec** [comment]
@ezekg Can you post the config you used to produce that behavior?

**Comment by ezekg** [comment]
@nateberkopec here are the relevant parts of my Puma config:

```rb
environment 'production'
persistent_timeout 30
threads 32, 32
workers 8
```

I'm using 2 Professional-M dynos. I was load testing ~60 RPS for 2 minutes. I saw some timeouts due to using rack-timeout and the timeout being set at 15s (expected timeouts due to volume). Could that be related here? I am rescuing `Rack::Timeout::Error` in some custom middleware, so not sure if Puma would ever see that error or if it would have any effect on these zombie threads.

**Comment by twalpole** [comment]
@ezekg Are you actually configuring Puma to do SSL or are you using Heroku SSL? If you're not actually configuring Puma to handle the SSL I don't think the issue you're seeing is the same.

**Comment by ezekg** [comment]
@twalpole I think you're right. My bad. I saw that https://github.com/puma/puma/issues/1565 was linked and figured they were related, but I guess they're not actually related after all. I'll open up a new issue when I get some time to create a reproducible test app that exhibits the behavior I'm seeing.
