### ISSUE TITLE
cannot load such file -- puma/state_file (LoadError) 

### ISSUE THREAD

**Issue by msuzoagu** [puma/puma#1931]
### Steps to reproduce

1) Given this app structure: 
```
.
├── Dockerfile
├── Gemfile
├── Gemfile.lock
├── Rakefile
├── app
├── app.rb
├── config
│   ├── boot.rb
│   ├── environment.rb
│   └── puma
│       ├── log
│       │   ├── puma_access.log
│       │   ├── puma_error.log
│       │   └── puma_example.log
│       ├── puma.pid
│       ├── puma.rb
│       ├── state
│       └── test.rb
└── config.ru
```

2) config/puma/puma.rb contains the following: 
```
  #!/usr/bin/env puma
  root = Dir.getwd
  current_dir = __dir__
  rackup "#{root}/config.ru"
  environment "#{ENV['APP_ENV']}"
  pidfile "#{current_dir}/puma.pid"
  state_path "#{current_dir}/state"

  stdout_redirect "#{current_dir}/log/puma_access.log", "#{current_dir}/log/puma_error.log", true

  threads 4, 8

  bind 'tcp://0.0.0.0:4567'

  activate_control_app
```

### Expected behavior
- starting the sinatra container via "puma -C config/puma" should launch the sinatra application with puma acting as webserver

### Actual behavior
Instead, container/service logs show failure to lauch puma due to inability to require 'puma/state_file'.  Complete output is below: 
```
testdocker@staging-docker-1:~$ docker container logs portfolio_sinatra.2.lkywflsgdxguoftugpq45zcde
Puma starting in single mode...
* Version 3.12.1 (ruby 2.6.2-p47), codename: Llamas in Pajamas
* Min threads: 4, max threads: 8
* Environment: "staging"
* Listening on tcp://0.0.0.0:4567
/usr/local/bundle/gems/puma-3.12.1/lib/puma/launcher.rb:111:in `require': cannot load such file -- puma/state_file (LoadError)
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/launcher.rb:111:in `write_state'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/single.rb:103:in `run'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/launcher.rb:186:in `run'
	from /usr/local/bundle/gems/puma-3.12.1/lib/puma/cli.rb:80:in `run'
	from /usr/local/bundle/gems/puma-3.12.1/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:23:in `load'
	from /usr/local/bundle/bin/puma:23:in `<main>'
```

Also run a test to get paths: 

```
testdocker@staging-docker-1:~$ docker run -ti --rm msuzoagu/portfolio_sinatra:staging /bin/sh
/srv/sinatra # ruby config/puma/test.rb
/srv/sinatra/config.ru
/srv/sinatra/config/puma/state
/srv/sinatra/config/puma
/srv/sinatra # ls /srv/sinatra/config
boot.rb         environment.rb  puma
/srv/sinatra # ls /srv/sinatra/config/puma/
log       puma.pid  puma.rb   state     test.rb
```

### System configuration

**Ruby version**: ruby '2.6.2'
**Rails version**: not a rails app but a sinatra app (sinatra version 2.0.7)
**Puma version**: puma 3.12.1 (tested with 4.0.1 and got same error)

**Comment by MSP-Greg** [comment]
This may be an issue with bundler/rubygems.  `require` is something that should just work.

I checked the gem, and `state_file.rb` is where it should be.  Also, the Bundler and RubyGems versions have bounced around in Ruby 2.6.x, as it was the first Ruby version with Bundler included in the std-lib.

Long story short, it might work correctly with 2.6.3.  A PR here could change the remaining `require` statements to `require_relative`, which bypasses the RubyGems/Bundler logic...

**Comment by nateberkopec** [comment]
It's a little weird that we do require in one place vs require_relative in another.

**Comment by nateberkopec** [comment]
@msuzoagu If you vendor Puma and then change that line (111 in launcher.rb) to require_relative, does it work?

**Comment by MSP-Greg** [comment]
JFYI, re `require_relative`, more info at https://github.com/rubygems/rubygems/pull/2425,  https://github.com/rails/rails/pull/29638, and https://github.com/rails/rails/pull/29638#issuecomment-321335175.

Summing up, if code can both `require` and `require_relative` the same file, issues may arise if the path contains a symlink.  This is not an issue with Ruby 2.5 and later.

If all the code in a gem was changed to `require_relative`, this wouldn't be a problem **unless** some of it's files were required by other code (ie, the app, another gem).

> It's a little weird that we do require in one place vs require_relative in another

I assume Puma plugins may require Puma files, so maybe everything should remain `require`.  I may changed some to `require_relative`...

**Comment by nateberkopec** [comment]
Nice, excellent cross-link to the Rails situation @MSP-Greg. That's very helpful.

**Comment by MSP-Greg** [comment]
One thing though, I think the bug noted did not cause a 'runtime error', it just reloaded the file.  Also, the above issue is with Ruby 2.6.2, so what I said was really JFYI.  I follow Ruby, RubyGems, and Bundler, and there were a lot of issue when Bundler was added.  I'm hoping 2.6.3 fixes the issue...

**Comment by nateberkopec** [comment]
@msuzoagu What fixed the issue for you?

**Comment by andrew-rocchi-welltok** [comment]
@nateberkopec 

I just started to have this issue, but only under certain specific circumstances.  Right now, I am running Puma in a Docker container, and it is treated differently depending on the startup.  What I have noticed is that this bug only appears for me when using the RubyMine Remote Debugger, and also only appears on my server, not in local development.

I haven't quite diagnosed why that is, however I was able to monkeypatch this by fixing the likely underlying (and super simple!) issue.  I'm not sure why the file is set up like this, but all of the require statements are `puma/...` instead of `...` . There is no puma folder from this directory, since the launcher.rb file itself is already in the puma folder.  This is apparent when using `require_relative`, which can be seen in the above comment with msuzoagu having their first error message show the path: `/srv/sinatra/vendor/gems/puma-3.12.1/lib/puma/server.rb:17:in `require_relative': cannot load such file -- /srv/sinatra/vendor/gems/puma-3.12.1/lib/puma/puma/puma_http11 (LoadError)`

This path shows `.../lib/puma/puma/puma_http11` instead of `.../lib/puma/puma_http11`
Changing the line from `require puma/state_file` to `require_relative state_file` fixed the issue for me, and I see that this is still the same in the current Puma version, so it would probably be worth changing this for the require statements in lib/puma/launcher.rb.

**Comment by sw4d** [comment]
Look, I'm only leaving this note because it has bit me in the rear several times, with just enough time spaced out between instances I forget what the fix is and snoop around issues like this in vain. 

If your development house is like mine, we use Passenger is production and Puma in development for certain projects.

I was getting this error because I pulled down a fresh copy of the repo and forgot to set the Gemfile to Puma instead of Passenger.
