### ISSUE TITLE
Don't mutate global STDOUT/STDERR

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1948]
...but don't break everyone's logging at the same time. https://github.com/puma/puma/pull/1946

**Comment by dentarg** [comment]
Recap

* The original attempt: https://github.com/puma/puma/pull/1837
* The issues it caused: https://github.com/puma/puma/issues/1906
* The revert: https://github.com/puma/puma/pull/1946

I wonder if the original attempt mostly(?) caused problems for people using demonization: https://github.com/puma/puma/issues/1906#issuecomment-522726659. Puma doesn't have demonization since version 5, so the code referenced in the linked comment no longer exist.

**Comment by dentarg** [comment]
@ccverak might be good to read through the above PRs/issues if you haven't already

https://github.com/puma/puma/issues/1906#issuecomment-523137933 mentions that Rails dropped `sync = true`, there's probably discussions about that in some issue over at https://github.com/rails/rails that one could learn from too
