### ISSUE TITLE
Remove daemonization

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1983]
Use systemd/upstart/a process supervisor instead.

**Comment by edmz** [comment]
Could you clarify this one? Is this only about removing all the daemonization code? or is it about doing more than just that?

**Comment by nateberkopec** [comment]
Only removing the code related to daemonization, correct

**Comment by edmz** [comment]
I noticed that @ioquatix on twitter mentioned 'systemd readiness protocol', so I gave it a look and it seems interesting. 

I [will link to his code](https://github.com/socketry/async-container/blob/master/lib/async/container/notify.rb) as a reference in case its useful somewhere down the road.

**Comment by nateberkopec** [comment]
Definitely. OFC any documentation we can add to help people make the transition would be great too, we already have some but can add more.

**Comment by sg552** [comment]
It's better to give an example in the documentation. thanks a lot!

**Comment by swistak** [comment]
Backwards incompatible interface breaking change in minor version. Naughty.

**Comment by montdidier** [comment]
I have to say I think this was a mistake.

**Comment by AlexWayfer** [comment]
> I have to say I think this was a mistake.

Without argumentation an opinion worth almost nothing, sorry.

**Comment by montdidier** [comment]
> > I have to say I think this was a mistake.
> 
> Without argumentation an opinion worth almost nothing, sorry.

Why? It was removed without argument?

**Comment by montdidier** [comment]
Smart assery aside. I don't know what the rationale behind its removal was, a quick look at the linked issues and PRs doesn't give me a strong indication or even argue for its removal. But whoosh it happened. What I do know is that it was convenient and worked well. It worked well for me and my team for at least the last 3-4 years of production use or so. So if we want to put some arguments down; off the top of my head.

- convenient
- easily controllable via existing Capistrano plugins and scripts
- standalone
- familiar
- largely operating system agnostic - we now have to configure different options for each monitoring system we might want to use. I usually use what is there on the operating system. So it defacto becomes one thing for various Linux distributions, something else for the flavours of BSD. There is already a small collection of contrib-scripts collecting for 5.x.x release(s) directly because of this decision.

**Comment by nateberkopec** [comment]
It was almost 700 lines that no one maintained and is no longer necessary for us to include in Puma because there are better options available. [Daemonization has not been a good application-level concern for a while now.](https://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/).

**Comment by montdidier** [comment]
I will have a read and see if I feel the same way afterwards. Thanks for the link.

**Comment by nateberkopec** [comment]
Thanks! Most of the reason I decided to drop this stuff from Puma was because of Mike's opinions, which I find are usually very very right in the long run ;)

**Comment by kigster** [comment]
I you fraking serious?
 
You removed something that worked perfectly well, JUST  because you think we should all switch to using upstart?

That's arrogant and ignorant. I'll be switching away from puma instead.

**Comment by kigster** [comment]
While I understand at some level that daemonization code was not bring maintained, that it was likely hard to test, I wish the solution would have been to extract this to a gem so that those of us using Puma without the upstart wrapers, can still run in the daemon mode.

Another direction I can see for this PR is including `systemd`, `launchctl`, and `upstart` configuration templates that can help people transition from the built-in daemon to those tools easier.

But in this case, *I feel that I must at the very least voice my **strong disagreement with the idea that the daemonization code in one of the most popular TCP/IP servers, which is supposed to run on the background in production, was optional**.

**Comment by kigster** [comment]
Acually, I am going to take a stab at the [puma-daemon](https://github.com/kigster/puma-daemon) Ruby gem.

**Comment by nateberkopec** [comment]
> Another direction I can see for this PR is including systemd, launchctl, and upstart configuration templates that can help people transition from the built-in daemon to those tools easier.

We have documentation and a template for systemd in the docs directory. It's not perfect OFC and we're open to PRs to improve. The deployment docs have always just been a collection of community wisdom and we merge pretty much anything that people propose.

[We removed the upstart documentation because upstart has been deprecated](https://github.com/puma/puma/pull/2408) and public support has been discontinued.

`launchctl` docs would be good.

More than happy to add any hooks or plugin infrastucture required to make `puma-daemon` work, if anything is missing. Thanks for taking up the effort.

**Comment by taf2** [comment]
So no more support for init.d

**Comment by kigster** [comment]
@taf2 @dentarg @nateberkopec @edmz Folks — I finished what appears to be a working compromise for daemonization. Please take a look - it's been extracted into the new Ruby Gem  [puma-daemon](https://github.com/kigster/puma-daemon). 

I would love some additional testing and real-world validation if you end up using it with Puma 5+. 

The gem does not support JRuby at the moment,  only MRI Ruby.

However, with rather small number of changes I was able to restore the daemonization if either A) you include `require 'puma/daemon'` in your Puma Configuration file, or if you start it via the `pumad` executable (which can swallow `-d` flags that are currently tripping standard `puma` executable.

**Comment by taf2** [comment]
@kigster this is great!   I'll try to get you some feedback this week.

**Comment by montdidier** [comment]
@kigster thank you. I'll give it a go in the next week or two hopefully.

**Comment by dillon-co** [comment]
> > I have to say I think this was a mistake.
> 
> Without argumentation an opinion worth almost nothing, sorry.

Definitely not true. This costed me many hours of wasted time switching from heroku to digital ocean

**Comment by dentarg** [comment]
but it was free

**Comment by kigster** [comment]
> but it was free

The daemonization functionality was definitely not free. It was different or MRI and JRuby, and and as the authors correctly asserted using systemd is much more reliable, allowed constraining system resources, and offers many additional benefits.

The gem [puma-daemon](https://github.com/kigster/puma-daemon) which I maintain offers the old functionality to MRI ruby.

I'd welcome any help addressing a small number of special case bugs in that gem, but many people are using it in development to bring back the old daemonization feature. That said, I would recommend relying on it in production. Use it in development if it makes your flow better, but for production please use better technology such as systemd or launchctl on OS-X.
