### ISSUE TITLE
Puma does not prefer idle-workers in cluster mode

### ISSUE THREAD

**Issue by ayufan** [puma/puma#2078]
**Describe the bug**

We at GitLab.com are production testing Puma with prepartions for switching to it.
However, we noticed a few oddness when running Puma vs Unicorn in mostly similar configurations.

An worker of Puma when running in Cluster mode has no knowledge about siblings and their utilisation. This results in some of the sockets to be accepted by sub-optimal workers, that are already processing requests. This does have a statistical significance as in my local testing, and GitLab.com testing in the above workload we see an increase of around 20-30% of durations on P60%. Which is a significant increase.

**Capacity of Puma**

Capacity of Puma web-server is defined by `workers * threads`. Each of these
form a slot that can accept a new request. It means that each slot can accept
a new request at random (effectively round-robin).

Now, what happens if we have 2 requests waiting to be processed and two workers,
and two threads:

1. Our total capacity is 4 (W2 * T2),
2. Each request can be assigned at random to any worker, even the worker that is
   processing currently request, as we do not control that,
3. It means that in ideal scenario if we have 2 requests, for the optimal performance
   they should be assigned to two separate workers,
4. Puma does not implement any mechanism for 3., rather it is first accepting, first wins.
   It does mean that it is plausible that the two requests will be assigned in sub-optimal
   way: to the single worker, but multiple threads.
5. If the two requests are being processed by the same worker, they do share CPU-time,
   it means that they processing time is increased by the noisy neighbor due to Ruby MRI GVL.

Interestingly, the same latency impact is present on `Sidekiq`, we just don't see it,
as we do not care about real-time aspect of background processing that much.

However, the scheduling changes can improve `Sidekiq` performance as well if we would
target `sidekiq` as well.

This is more described in detail here: https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8334#note_247859173

**Our Configuration**

We do run Puma and Unicorn in the following configurations:

1. Puma runs in `W16/T2`, the `16` corresponds to 16 CPUs available, nodes do not process anything else,
2. Unicorn runs in `W30`, the `30` seems like some artificial factor taken to have some sort of node saturation,
3. The nodes are lightly utilised, peeking at around 45% of CPU usage,
4. We seem to process around 70-80rq/sec.

We did notice oddness in Puma scheduling, as it was sometimes hitting the workers that are already processing requests. This resulted in increase of latency and duration of requests processing, even though we had a ton of spare capacity on other workers that were simply idle.

The nodes are configured today like that, due to graceful restart/overwrite/shutdown of Unicorn, to have a spare capacity to handle as many as twice amount of regular `W30`. They are highly underutilized on average due to that, but this is something to change. 

**Data**

The exact data are presented here: https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8334#note_247824814 with the description of what we are seeing.

**Expected behavior: Ideal-scheduling algorithm in multi-threaded scenario**

In ideal scenario we would always want to use our capacity efficiently:

1. Assign to free workers first, as they do offer the best latency,
1. Assign to workers with the least amount of other requests being processed, as they are the least busy,
1. Assign to workers that are close to finish the requests being processed, as they will have a free capacity in the future (this is hard to implement, as this becomes a quite complex heuristic to understand the request completion time).

Currently, Puma does nothing from that. For round-robin we pay around 20% of ~performance penalty due to sub-optimal request processing assignment.

It is expected that the closer we get to 100% CPU-usage the more expected is that the Puma-non-scheduling algorithm will not be a problem, due to node being saturated, and threads by balanced by the kernel.

**Workaround or Solution?**

I started exploring an simplest solution for that in this issue:
https://gitlab.com/gitlab-org/gitlab/issues/36858.

This adds a very small sleep into busy-workers. This results in busy workers in delaying accepting
socket, and give time for idle-workers to do it first, as they should be fairly quick to respond in such cases, as they are not processing anything significant.

This has surprising results as it seems to allow to remove this performance penalty and prefer to evenly distribute across workers first, instead of round-robin as it is happening across all workers and all threads today. This is more described here: https://gitlab.com/gitlab-org/gitlab/issues/36858#note_247918506.

This is a proof of concept: https://github.com/ayufan-research/puma/commit/e0699024e699e7733c89c2dd7fc06ef942a8696f.

It seems that a delay as small as `1ms` does a trick. Well, it does not seem to
be `1ms` specifically, due to Ruby and kernel ticks, which can be as long as 10ms.
However, it is significant enough to make idle-worker to be always first responder.
We should not really loose any performance, as busy-worker-that-is-sleeping is already
processing request, so it is doing something.

Some non-scientific tests are here: https://docs.google.com/spreadsheets/u/2/d/1y2YqrPPgZ-RtjKiCGplJ7YkwjMXkZx6vEPq7prFbUn4/edit#gid=0
Test script is here: https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8334#note_247859173

**Comment by ayufan** [comment]
Any other ideas what we could do to make it better? :)

**Comment by dentarg** [comment]
@ayufan have you seen https://github.com/puma/puma/pull/1920? (and https://github.com/puma/puma/issues/1254, https://github.com/puma/puma/pull/1646)

**Comment by ayufan** [comment]
@dentarg 

Thanks. This slip my eyes. Yes, it describes the same problem pretty much. 

Should we close this one?

How close is the #1920 till finish?

**Comment by ayufan** [comment]
OK @dentarg 

Looking at the #1920 it does not seem to solve idle-worker problem, as this assumes that the new connections are delayed before getting accepted until there's at least one thread available.

I will run the #1920 against my performance testing to see exactly if and when it helps.

**Comment by travisbell** [comment]
Great writeup @ayufan. I recently switched from Unicorn to Puma on TMDb (16,000+ r/s) and noticed the issues described in #1254 but didn't take the time to put everything together like you did here. I just took the utilization/latency hit and moved on.

It would be great if this could improve. I made the choice to stick with Puma for reasons that outweighed the difference I noticed. But I'd sure be happy to see it improve.

**Comment by ayufan** [comment]
@travisbell Could you test this PoC https://github.com/ayufan-research/puma/commit/e0699024e699e7733c89c2dd7fc06ef942a8696f? I did not yet to get to running that on production, but I was able to reproduce the issue locally and see that this does improve it.

**Comment by ayufan** [comment]
I created the https://github.com/puma/puma/pull/2079. Which implements the above proposal, instead of using `sleep` it uses conditional variable with timeout which is much better as this gets signaled once one of the threads finishes the work.

**Comment by nateberkopec** [comment]
It's an interesting solution to the problem. You're literally sleep-sorting Puma workers, which is diabolical, but if it works, it works, right?

I'll ask @evanphx what he thinks.

**Comment by ayufan** [comment]
@nateberkopec I merged that to GitLab. We will be testing that in a few days on a production. We had a great run in staging and canary showing that patch helps significantly. Once I have data I will post it here with more explanation and comparison of different modes. I'm waiting for that before adding and doing more work on this PR.

**Comment by nateberkopec** [comment]
Love it. Eager to hear back.

**Comment by ayufan** [comment]
I'm closing this issue as we have PR: https://github.com/puma/puma/pull/2079 with all description moved.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
One thing I came across was [this LWN article on SO_REUSEPORT](https://lwn.net/Articles/542629/), specifically:

> The problem with this technique, as Tom [pointed out](https://lwn.net/Articles/542718/), is that when multiple threads are waiting in the accept() call, wake-ups are not fair, so that, under high load, incoming connections may be distributed across threads in a very unbalanced fashion. At Google, they have seen a factor-of-three difference between the thread accepting the most connections and the thread accepting the fewest connections; that sort of imbalance can lead to underutilization of CPU cores. By contrast, the SO_REUSEPORT implementation distributes connections evenly across all of the threads (or processes) that are blocked in accept() on the same port.

That seems to match the symptoms we saw here.

I wonder if `SO_REUSEPORT` would load balance `accept` more evenly. If so, it may make sense to re-evaluate https://github.com/puma/puma/issues/1307.

**Comment by schneems** [comment]
> I wonder if SO_REUSEPORT would load balance accept more evenly. If so, it may make sense to re-evaluate https://github.com/puma/puma/issues/1307.

I begrudgling know about `SO_REUSEPORT` due to some work on https://github.com/puma/puma/issues/3487. In the process of researching I found that:

- Nginx has the ability to use this option, but it's off by default
- gunicorn (python) Introduced it and then also made it not default https://gist.github.com/schneems/af455d13f3e96487de8cba68648dc1ab.

The biggest problem seems to be development ergonomics where two servers accidentally start on the same port and instead of saying "ohno, I can't use this port". Then when you visit localhost:3000 approximately half of your requests are served by the server you're expecting and half are served by 🤷

Docs on that option https://man7.org/linux/man-pages/man7/socket.7.html

          SO_REUSEPORT (since Linux 3.9)

              Permits multiple AF_INET or AF_INET6 sockets to be bound
              to an identical socket address.  This option must be set
              on each socket (including the first socket) prior to
              calling [bind(2)](https://man7.org/linux/man-pages/man2/bind.2.html) on the socket.  To prevent port hijacking,
              all of the processes binding to the same address must have
              the same effective UID.  This option can be employed with
              both TCP and UDP sockets.

              For TCP sockets, this option allows [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html) load
              distribution in a multi-threaded server to be improved by
              using a distinct listener socket for each thread.  This
              provides improved load distribution as compared to
              traditional techniques such using a single [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html)ing
              thread that distributes connections, or having multiple
              threads that compete to [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html) from the same socket.

              For UDP sockets, the use of this option can provide better
              distribution of incoming datagrams to multiple processes
              (or threads) as compared to the traditional technique of
              having multiple processes compete to receive datagrams on
              the same socket.

I don't know how using `SO_REUSEPORT` would compare to the solution we chose (adding a small sleep value). It would be helpful for someone to explore that. I.e. are people reading "SO_REUSEPORT is good" and then paroting that, or is there a real, measurable benefit in adopting it?

If we can get some real, compelling evidence that it's a worthwhile optimization to allow then I think I would support reconsidering it.

Ideally though we would add safeguards to prevent the failure I described above. Even if it's off by default, it would 100% trip me up and be really hard to debug if I found myself in that situation by accident.

The docs say that running it as a different user is a protection. That seems like a security measure and not a guardrail to be. We could do something with a file-based advisory lock. I wonder if any other servers have done something for the UX here. I think we would not be able to make it 100% safe, the question is whether or not we could make it slightly safer, without introducing new UX headaches.

But again, that's all moot if there's not real, measurable, performance benefits from using that option.

**Comment by schneems** [comment]
Adding to my prior comment. From that LWN article:

> is that when multiple threads are waiting in the accept() call, wake-ups are not fair,

The way Ruby's accept is written, it doesn't block and wait it uses https://rubyapi.org/o/socket#method-i-accept_nonblock., which uses `O_NONBLOCK`.  If we were blocking, then there would be more contention in the system call and the OS would use a FIFO method for waking the first process to call `accept` (IIRC). Switching to SO_REUSEPORT reduces that contention by providing a completely different queue for each process. The traditional FIFO "inherit socket from parent" is associated with a single queue which comes with lock contention and CPU cache line bouncing to reduce performance. However, that wouldn't result in 50% of CPU sitting idle.

That realization reinforces that SO_REUSEPORT is related to this class of problem, but is fundamentally not the same thing.

Knowing that the accept is called in a non-block loop, we have N processes racing for the next request to come in. With the logic here, if a process has nothing to do, it will loop as fast as possible (zero sleep). A process with work will see some delay.

The GIL/GVL is brought up in the notes. I think that's related but not the primary issue here. It looks like the accept loop is called in it's own thread and there doesn't seem to be a scenario (that I can find) where Ruby's choice of thread to execute with the GIL would result in a delay for another process receiving the next request in the queue (confidence at maybe 75%, I'm willing to take new evidence). 

There's likely an effect of the sleep hinting to Ruby that the accept loop is less important than another thread that's actually working on processing a request due to the GVL. But I'm not sure how to quantify that. I think in practice it means that if there's another Ruby thread waiting to execute, then the accept loop would sleep for at least one full quanta and possibly multiple quanta while multiple threads try to finish (if all work was CPU bound, which is easier to describe). I think that might indirectly translate to "the more busy the server, the longer the sleep," which gives us a more tiered "sleep sort" than the off/on logic presented here. 

The eventual sleep optimization has stood the test of time, but it's also quite difficult to reason about or modify. I'm hoping that some of my notes here might give hints to future maintainers/contributors (possibly me even) on separating out the theories from the facts. Ideally if we could isolate with some more specificity the exact things causing the slowdown, we could work to remove this sleep. I'm glad that it's here and glad that it seemingly works, but it's taking a disproportionate of my puma brainspace.
