### ISSUE TITLE
Hot restart under JRuby

### ISSUE THREAD

**Issue by peterdk** [puma/puma#210]
According to the wiki a hot restart is not yet supported under JRuby.

Any idea when this will be the case? Is it planned to be added? Or will this never work?
It's the only reason for not switching from unicorn.

**Comment by jeremyhaile** [comment]
I don't understand. So JRuby is one of the recommended Ruby platforms to run puma, but there is no way to do a hot restart?  

Has anyone found a workaround for this? Are there other recommended rails servers that do support hot restart on JRuby?

**Comment by evanphx** [comment]
@jeremyhaile I clarified in the issue that puma does support restart on JRuby

**Comment by jeremyhaile** [comment]
@evanphx I guess I'm just wondering if there was a workaround or what people were doing to address that, since JRuby is a common platform for puma. Or if there were any plans to support some type of hot restart on JRuby.

It looks like we'll have to switch to passenger if I can't find any other options. Even the open-source passenger supports "hot restart" (in puma's terminology).  You need Enterprise passenger for phased restarts.  But before I did that I wanted to see if anyone had found a workaround with puma. (other than rolling our own proxy/multiport solution)

**Comment by evanphx** [comment]
@jeremyhaile Puma right now supports "hot restart" on JRuby but it is at the whim your JVM to support the ability to pass file descriptors between processes properly. I'm unable to test every JVM but it does work in the common cases I've tested.

**Comment by jeremyhaile** [comment]
@evanphx ok - good to hear it does support hot restart. It wasn't working for me on JRuby 9.0.1.0 on Mac OS X Capitan. Thanks for responding so quickly.

**Comment by thapakazi** [comment]
long time no see. any update on this one ?

@evanphx Is it possible, you could explain your methods of doing **hot restarting PUMA with JRUBY** || we have a something easy to work with added by now...
