### ISSUE TITLE
4.3.2 Unable to set cookie

### ISSUE THREAD

**Issue by bmclean** [puma/puma#2132]
**Describe the bug**
After upgrading to Puma 4.3.2, setting a cookie from within a controller action fails to create the cookie.

Example:
```
  def create
    cookies[:prompt_dismissed] = { value: true }
    redirect_to users_path
  end
```
Might be similar cause to #2131

**Comment by bmclean** [comment]
If I comment out line 685 of server.rb setting cookies works correctly.
```
# headers.reject! { |_k, v| CRLF_REGEX =~ v.to_s }
```

**Comment by ideasasylum** [comment]
I encountered a similar problem which [Nate tweeted out](https://twitter.com/nateberkopec/status/1233172403389259782)

![CleanShot 2020-02-27 at 23 22 53](https://user-images.githubusercontent.com/14988/75497504-58659f00-59bc-11ea-9643-015ee3720b03.png)

In my case, it looks like the cookie path is being set incorrectly to `/\n`. I just need to figure out where that's being set.

We're on Rails 5.2.4.1

**Comment by esb** [comment]
Yes, we have a problem here.

Using a standard Rails controller which sets a cookie may result in multiple cookies being set in the header. It's been reported that Rack joins these headers with "\n" so this security fix will totally supress all the cookie headers being sent.

This has nothing to do with including "\n" within the cookie value, but gets generated as part of the rack environment. 

Potentially this breaks all Rails apps that use cookies, so it probably needs to be addressed fairly urgently.

**Comment by nateberkopec** [comment]
In the meantime, folks can use the workaround mentioned in the CVE and modify the regex to catch only CRLF rather than CR or LF.

**Comment by nateberkopec** [comment]
Hm. So I literally just [copied the regex used in WEBrick](https://github.com/ruby/ruby/blob/3556a834a2847e52162d1d3302d4c64390df1694/lib/webrick/httpresponse.rb#L412), so I'm a little surprised to see that this breaks so many apps. If we have a problem, WEBrick has a problem, which I would've guessed would have been caught already.

I'll have to go back and learn more about the vulnerability. I think we maybe don't need to catch _only_ LFs or _only_ CRs but purely a CR followed _at some point later in the same header_ by an LF? But then perhaps you could put a CR in one header and an LF in another, later header? 

Patch will be out tomorrow. Again, in the meantime, either rollback to 4.3.1 if you can be certain you do not have user input in header values or use the workaround here: https://github.com/puma/puma/security/advisories/GHSA-84j7-475p-hp8v with a modified regex (`/\r\n/` instead)

**Comment by fukayatsu** [comment]
https://github.com/fukayatsu/debug-puma-4.3.2-cookie

I created a repo to reproduce this issue.


### WEBrick 1.6.0 / ruby 2.7.0 (2019-12-25) [x86_64-darwin19]

```
$ bin/rails server -u webrick
# => WEBrick 1.6.0 ruby 2.7.0 (2019-12-25) [x86_64-darwin19]
$ open http://localhost:3000/
# => `Set-Cookie` headers shown on devtool.
```

<img width="1025" alt="ss_2020-02-28_15_50_40" src="https://user-images.githubusercontent.com/1041857/75517773-db313d00-5a42-11ea-89d2-13a37f5381d7.png">


### puma Version 4.3.2 (ruby 2.7.0-p0), codename: Mysterious Traveller

```
$ bin/rails server -u puma
# => puma Version 4.3.2 (ruby 2.7.0-p0), codename: Mysterious Traveller
$ open http://localhost:3000/
# => `Set-Cookie` headers not shown on devtool.
```

<img width="695" alt="ss 2020-02-28 15 50 02" src="https://user-images.githubusercontent.com/1041857/75517801-ec7a4980-5a42-11ea-92bb-df1cadda2b07.png">

### puma Version 4.3.1 (ruby 2.7.0-p0), codename: Mysterious Traveller

```
$ git checkout puma-4.3.1
$ bin/rails server -u puma
# => puma Version 4.3.1 (ruby 2.7.0-p0), codename: Mysterious Traveller
$ open http://localhost:3000/
# => `Set-Cookie` headers shown on devtool.
```

<img width="1113" alt="ss_2020-02-28_16_00_40" src="https://user-images.githubusercontent.com/1041857/75518150-98239980-5a43-11ea-8e71-94bd80a8143a.png">

**Comment by fukayatsu** [comment]
> https://twitter.com/nateberkopec/status/1233228543133249537
> It looks a little more complicated. Rack is inserting /n in headers, which I didn't expect, because I just copied WEBrick's fix. Maybe hold off on upgrading until I can get a 4.3.3 out tomorrow.

👍

**Comment by P9GIT** [comment]
We also experience app breakage with this update.
Our login page ceased to work.

Reverted to 4.3.1 makes it work again.

**Comment by karol-blaszczyk** [comment]
We experiencing the same issue. Login doesn't work. We keep 4.3.1

**Comment by gingerlime** [comment]
Seeing this also with 3.12.3 :(

**Comment by 9mm** [comment]
Dude what... I just deployed and didn't do a test because it was a minor version bump, and our entire order flow depends on cookies/session.

For me it was upgrading to 3.12.3. This is super bad, why is this not fixed within literally minutes?

**Comment by gingerlime** [comment]
The odd thing for us was that it didn’t actually break logins in staging and live but it did in development ... or maybe the upgrade didn’t take place fully with phased restarts? In any case we reverted the change for now

**Comment by summera** [comment]
Same issue here after testing the update - can't sign in to app due to cookie issues.

**Comment by ideasasylum** [comment]
@9mm our order flow depends on cookies too, and logins, and customer support etc — just like everyone else's app. But we all have to take responsibility for the things we deploy. It's no one else's fault when our app breaks—certainly not the puma maintainers

**Comment by 9mm** [comment]
@ideasasylum I understand, and agree. I largely implied that in my post (that it was my fault). I was more speculating why this wasn't a bigger deal, as it breaks probably 85-90% of sites. I'm not the maintainer of everything, but that seems like a patch would be released pretty urgently

**Comment by nateberkopec** [comment]
@9mm I am working on US Central Time. This was reported 19 hours ago at 6pm CST, and for 8 out of those 19 hours I have been asleep. The other 11 hours, I have been working on and thinking about a fix for this bug. You didn't even have to pay me!

**Comment by 9mm** [comment]
> @9mm I am working on US Central Time. This was reported 19 hours ago at 6pm CST, and for 8 out of those 19 hours I have been asleep. The other 11 hours, I have been working on and thinking about a fix for this bug. You didn't even have to pay me!

😆Please dont misinterpret anything I've said as expecting anything or being entitled to anything. Thanks for your contributions!

PS. I love your Rails performance book, keep up the awesome work

**Comment by nateberkopec** [comment]
Fix is on master. 4.3.3 and 3.12.4 will be out within an hour or so. Thanks for your patience everyone.

**Comment by bmclean** [comment]
Thank you @nateberkopec! We have 4.3.3 deployed on our staging environment and everything looks good.

**Comment by nateberkopec** [comment]
4.3.3 and 3.12.4 have been pushed to rubygems.org. In addition to a fix for this issue, I fixed [an additional vulnerability in Early Hints](https://github.com/puma/puma/security/advisories/GHSA-33vf-4xgg-9r58). Thanks to @matthewd for helping me with this issue and that vulnerability.

## Why was a bug that broke so many applications included in a patch (security) release?

The simple root cause is that Puma did not have test coverage around [this line](https://github.com/puma/puma/blob/fa80c790322a556a8a16274b13ac5e50f37926aa/lib/puma/server.rb#L780), which ensures that we conform to [the Rack spec](https://github.com/rack/rack/blob/master/SPEC.rdoc#the-headers-) around header splits. Of course, we do now.

In a Rack-compatible web-server, we're supposed to take a hash that looks like this:

```
"X-Header": value1\nvalue2
```

...and turn it into:

```
"X-Header": value1
"X-Header": value2
```

It turns out this feature of Rack is particularly widely used to set cookies, which makes sense, because a lot of different parts of the app want to touch the cookie headers. That's why all of your logins broke.

If we had test coverage around the (one!) line that split headers on newlines, 4.3.2 wouldn't have passed that test and I would've eventually figured out what was going wrong.

I copied the fix from WEBrick, but I didn't realize that WEBrick is not a Rack-compatible webserver, and so they can do things a little differently than we do in Puma.

## What can be done to prevent something like this in the future?

With security patches especially, it's hard to get good "real-world" testing on a release. With a lot of our performance patches or releases, for example, we try those out on our own applications to make sure they work. With security patches, we have to be kind of careful about testing them because we could leak the vulnerability before we're ready.

Instead, Puma clearly needs more test coverage around Rack compliance. I haven't looked yet, and I don't know how much more is untested, but with just one more test in the right place this would've been caught. Issue #2137 has been created to track this and if you'd like to contribute, we'd love your help.

**Comment by ohaddahan** [comment]
Thanks @nateberkopec for the awesome patch!

I followed your link [headers-spec](https://github.com/rack/rack/blob/master/SPEC.rdoc#the-headers-) and I see they mention the entire range under [ASCII 37](http://www.asciitable.com/).

I checked and this `/[\u0000-\u0025]/` seems to work and cover this requirement how it helps somehow.

```ruby
"1\n2\r3 4! 5$6%".scan(/[\u0000-\u0025]/)
[
    [0] "\n",
    [1] "\r",
    [2] " ",
    [3] "!",
    [4] " ",
    [5] "$",
    [6] "%"
]
```

**Comment by P9GIT** [comment]
@nateberkopec 
Thanks for your awesome work! :1st_place_medal:
Really appreciated.

**Comment by lmansur** [comment]
We've been running 4.3.3 without any problems. Appreciate the quick fix, Nate 👍
