### ISSUE TITLE
Remove tcp mode (lopez mode)

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2164]
Also remove tests + docs.

Basically tcpmode was added as experiment 7 years ago, no one used it or contributed/added to it, and it has only increased maintenance burden since. So, it's out.

**Comment by indirect** [comment]
@nateberkopec since TCP mode is on the way out, how do you feel about (independently, and right away) changing the console message from `* Listening on tcp://0.0.0.0:9292` to http:// instead? That would make it possible to cmd-double-click on the message Puma prints to open it immediately in a browser, which I miss a lot.

**Comment by nateberkopec** [comment]
Love it. I'll open another issue.

**Comment by eregon** [comment]
I had the exact same thought :)
