### ISSUE TITLE
Thread safe mode

### ISSUE THREAD

**Issue by ioquatix** [puma/puma#2171]
I'm considering the future of Rack 3.

I believe it could be prudent to declare that individual `app` instances are not thread safe.

This would mean that it wouldn't be valid to invoke `app.call(env)` from different threads, nor would it be re-entrant.

I've been experimenting with this in falcon. Per-process or per-thread instance of app. In my limited testing it works fairly well. The overhead is a few extra objects allocated per thread.

A `preload.rb` file can be used to preload any gems or other code into the parent process if desired (e.g. only in production).

I was wondering if you'd be interested to experiment with this too. Perhaps adding `puma --thread-safe` as an option, which creates one instance of app per thread/worker.

Interested to hear your thoughts too. Maybe you already tried this in the past, or maybe it's already implemented.

**Comment by nateberkopec** [comment]
This is mostly a "no" for me.

Thread-safety problems as actually experienced by users of Puma fall into two buckets:

1. If the Rack middleware stack of Rails was completely frozen (i.e. rack-freeze) by default, we'd eliminate 90% of the threading bugs people report.
2. The other 10% is people assigning database connections to constants or globals, which is really easy to fix and find.

Creating a new application instance would fix both of these problems, but it seems to me like really heavy-handed solution. Problems I anticipate:

1. I think you're underestimating the object allocation burden here, especially with many threads. Mature Rails applications can easily allocate 4 million objects or more on startup.
2. This also duplicates all internal caches and memoization, which will hurt performance. Instead of 1 memoization/cache, you now have N of them.
3. Constants/globals (one of the thread safety issues mentioned) for database connections will break outright rather than cause threading bugs, or possible still cause threading bugs with a constant redefinition warning, which I guess is OK but then they'll just fix the issue and don't need thread-safe mode anymore.

From _my_ perspective, if Rails just froze it's middleware stacks we wouldn't have an issue with threadsafety in the Rack ecosystem (or maybe Rack can provide a middleware stack class which does this for you).

**Comment by nateberkopec** [comment]
OFC my performance concerns here are all testable/falsifiable, but even if they're not valid, doing this at the Rack level seems like a heavy-handed solution for a simple problem.

**Comment by ioquatix** [comment]
> heavy-handed solution for a simple problem.

I'm not convinced that this is a heavy-handed solution for a "simple problem". Based on my actual code analysis, this problem is far from simple. Not criticising your opinion, maybe I'm wrong.

> This also duplicates all internal caches and memoization, which will hurt performance. Instead of 1 memoization/cache, you now have N of them.

That's assuming a cache per app. The other option if apps really want a shared global cache, is to use a global.

What I noticed was that I ended up going through my apps and changing `{}` to `Concurrent::Map.new`. Not sure if I'd be okay with N threads * memory usage. But at least this can be validated.

> This is mostly a "no" for me.

So, even if you implemented it, you can still default to a single app for a cluster of workers, but with an extra option `--thread-safe` for experimenting.

**Comment by nateberkopec** [comment]
I'm OK with it as an app-server option, I think that's an interesting experiment, but you presented it as something coming from the Rack standard and I don't agree that app.call should be considered always-thread-unsafe in Rack, which is what you seem to be proposing.

**Comment by ioquatix** [comment]
Here is what I'm proposing for Rack 3

> https://github.com/rack/rack/issues/1617#issuecomment-597342562

**Comment by nateberkopec** [comment]
Thanks. We'll move discussion there.
