### ISSUE TITLE
Memory leak 4.3.3

### ISSUE THREAD

**Issue by vitalinfo** [puma/puma#2179]
We did update our production servers a few days ago with Puma 4.3.3 and in a few hours noticed that have a big troubles with memory usage.

<img width="306" alt="Screen Shot 2020-03-12 at 4 56 45 PM" src="https://user-images.githubusercontent.com/7523182/76535655-df6a4b00-6483-11ea-94a5-de4afd219fcc.png">

After downgrade to previous version (4.3.1) everything works fine.

**Comment by nateberkopec** [comment]
[It's not Puma.](https://github.com/puma/puma/compare/v4.3.1..v4.3.3) Nowhere for memory to leak there.

**Comment by nateberkopec** [comment]
If you go search for "memory leak" in our issue tracker, you can find some more help for debugging this issue. It's never Puma 🤷‍♂ .

**Comment by vitalinfo** [comment]
@nateberkopec how you can explain normalization of memory after if deploy include only downgrading Puma?

**Comment by nateberkopec** [comment]
How can you explain a memory leak when all we added was checking a string against a regex?

Also, note how on your graph only 1 dyno increased in memory usage. Your average use curve is a lot lower, which means that other dynos didn't experience the same issue.

If you really had a leak in Puma's request core, every single dyno would have been leaking (also, we would have had this reported a week ago, because this code is running on millions of requests per minute on people's servers rn)

**Comment by dentarg** [comment]
@vitalinfo I did the search Nate suggested, see  https://github.com/puma/puma/issues/1600#issuecomment-468291010

**Comment by wordjelly** [comment]
@nateberkopec 

I've read a lot of your posts all over the internet on malloc and its varied problems, Puma, fragmentation, making a case for jemalloc.

I've seen your list of known gems that have memory leak issues. I've also gone so far as to read a very old post you wrote about how Hashie::Mash has memory leak problems. 

My setup uses heroku + puma + Hashie::Mash (as i use Elasticsearch). 

I've switched to jemalloc, bypassed any calls to Hashie::Mash, made sure i don't use any of the "leaky" gems in your list. I've been at this for nearly 4 days.

All said and done, I'm seeing something very similar to @vitalinfo. There is a slow and constant leak of memory on my Puma server, approximately 1 mb every hour. At the rate its going, I will have to restart my servers every couple of days.

Memory is never released, max total does not seem to stabilize. Is there anything I can do other than what you advised @vitalinfo

**Comment by dentarg** [comment]
@wordjelly have you investigated your app with any of these tools? https://github.com/schneems/derailed_benchmarks, https://github.com/SamSaffron/memory_profiler

**Comment by nateberkopec** [comment]
For me to take a memory leak issue seriously, I think I'd need to see a reproducing app with a constant linear leak that was easy to see per-request (e.g. this leaks 12 kb per request). Especially in this particular case, with a very simple code change allegedly causing a leak. Without a repro, we're debugging other people's stories through the internet and it's not a great use of our time, because in the past it's never been Puma's fault.

A leak in Puma will display the following characteristics:

1. Constantly growth over time (not sudden increases, not logarithmic, not exponential), varying with request rate
2. _All_ servers will see the same leak

After we've established those two facts are true, we can move on to getting a repro.

If you don't have these issues, you don't have a leak in Puma, so you're outside the scope of this issue tracker.
