### ISSUE TITLE
Cluster mode over large number of threads. Which one to choose?

### ISSUE THREAD

**Issue by zaknuces** [puma/puma#2290]
I have recently started using PUMA and I have a question regarding "Cluster Mode". 

Given two configurations, which one is preferred.

Configuration A (no worker):
threads 40, 50

Configuration B:
threads 10, 12
workers 4

Looking at the documentation, the cluster mode will create roughly the same number of threads (4 * [10 - 12]). 

1- Under which scenario it is recommended to use workers? Does create a sub-process (which is what workers are doing internally) have any additional benefits over the other in a multi-core processor environment?

2- Is using a lower number of threads with workers improves memory management? 

Putting this question to see if anyone faced the same existential crisis before.

**Comment by dentarg** [comment]
> Putting this question to see if anyone faced the same existential crisis before.

Pretty sure many already have... have you tried some internet searches? 😉 

I think [the general consensus](https://www.speedshop.co/2017/10/12/appserver.html) is that you should use some workers, so you are not hindered by [Ruby GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock).

However, it also depends on the use-case of your application. I'm not using workers in one of my apps, because of the type of work the application are not hindered by the GIL.

**Comment by nateberkopec** [comment]
@dentarg's link to my article sums up my thoughts on the matter if you are using MRI.

**Comment by zaknuces** [comment]
Thanks, folks! Just to add more info, I am using JRuby.

**Comment by nateberkopec** [comment]
Ah OK, very important detail. I am not really sure of the effects of threadcounts on memory with the JVM, it's something I haven't gotten to study in a production environment yet. It will definitely be different than MRI because the GC and allocation process is completely different.

If you are using JRuby, `worker`-based (cluster) configurations are not possible, because JRuby does not implement `fork`. So I think that answers your question.

**Comment by maxence33** [comment]
One related question : when a CPU has 8 cores and 16 threads. 
If we run Puma with Ruby MRI in clustered mode, should we spawn 8 workers or 16 workers ?

**Comment by dentarg** [comment]
@maxence33 it is not that simple, read https://www.speedshop.co/2017/10/12/appserver.html

**Comment by maxence33** [comment]
Hi @dentarg 
Well I have read it but Nate, when he is reffering to the CPU only mentions cores.
As CPU nowadays show the physical cores but also " virtual threads" which always equates to the double amount of physical cores.
Because I suspect we can't deactivate those "threads" I have been wondering if we should match the threads or the physical cores (I am not really doing math yet to know if I Max the Puma workers I will bottleneck somewhere else.. just wondering what is the actual usable number of cores)

**Comment by dentarg** [comment]
@maxence33 I see, I assume you are talking about [Hyper-threading](https://en.wikipedia.org/wiki/Hyper-threading) and the likes, and if so, your operating system will report that is has 16 [processors/cores](https://ruby-doc.org/stdlib-2.6.5/libdoc/etc/rdoc/Etc.html#nprocessors-method). My guess is that you should read "CPU cores" from Nate's article as the number of processors/cores your OS reports.

(I thought you asked if you could just set your worker count to your processor/core count. It is more complicated than that, it depends on your app.)

**Comment by maxence33** [comment]
Thank you @dentarg Indeed this is what I wanted to know. I plan to build a small home server with a Ryzen or a similar CPU and I didn't know what I should consider. I haven't purchased this new CPU yet, but my old Core I7 4790 is showing 4 cores on Linux `Hardinfo` as it is given for 8 threads on websites like Cpubenchmark. Then I guess I have to consider the Real physical Cores and not the threads..
Yet afaik if I pick a a Ryzen 5 3600 I can have 6 Puma workers at most ... Or if I pick an old HP Z620 with dual Xeon I can reach 12 physical cores and have 96GB of Ram for the same price (yet it would be  an 8-10 year old second hand setup, so not too sure)
Thanks a lot for your info ! Also I will read again Nate article to make sure it sinks in .. and try to find the best solution for my little home server

**Comment by aakashkaji** [comment]
Dear folks,

I'm always facing latency issues when sidekiq jobs are running.

My puma configuration as below
threads 0. 32
workers 2

Please suggest to me the best configuration of threads/workers so that server can handle 1000 requests simultaneously.

**Comment by dentarg** [comment]
@aakashkaji It is not that simple, you need to do your own research (or hire an consultant).
