### ISSUE TITLE
Proof-of-concept: Puma and relayd on OpenBSD

### ISSUE THREAD

**Issue by anon987654321** [puma/puma#2298]
Hey guys! Just finished work on this proof-of-concept server setup, thought I'd share it here first before I turn it into a pull request for the docs later on:

https://gist.github.com/anon987654321/4532cf8d6c59c1f43ec8973faa031103

Thanks!

**Comment by nateberkopec** [comment]
Thanks for reaching out. If I'm correct, it looks like the Puma configuration here is pretty simple (basically just listen on a particular port with a particular key/cert). The real heavy lifting here is httpd/relayd/OpenBSD. I'm not sure it would be an appropriate addition to our docs because you could very easily achieve a similar setup with any Rack web server.

What do you think?

**Comment by anon987654321** [comment]
Greetings!

I partly agree, because the OpenBSD rc.d shell script is tailored to fit Puma and which you won't find anywhere else. However, to get it working, one must use relayd, also whose setup can't be found anywhere else. 

The rest however, as you elude to, can be omitted and will be by the time I submit a pull request. I hope this is alright.

**Comment by dentarg** [comment]
Perhaps we can link the gists from the README at https://github.com/puma/puma#deployment?

**Comment by basicfeatures** [comment]
Hi y'all,

There's been a major upgrade to this setup: https://github.com/basicfeatures/openbsd-rails

Cheers!
