### ISSUE TITLE
Kubernetes downscale result in 5xx for the pods that have been killed

### ISSUE THREAD

**Issue by linkyndy** [puma/puma#2343]
**Describe the bug**
We are running an API using Puma in a Kubernetes cluster that uses a Horizontal Pod Autoscaler (HPA). We noticed that whenever the HPA scales down, the downstream services consuming our API get a 5xx error response, one for each of the pods that got killed in the process. 

We've added puma-metrics and see that the running number of threads is well below the maximum configured, whenever the errors occur. Requests are farily quick (<200ms), so it's not that the graceful shutdown timeout is exceeded. 

It looks like requests are thrown away/not fully processed after a graceful shutdown triggered by Kubernetes.

We don't know where to dig further, so I was curious to learn more about this, and maybe about the Puma internals, so we can spot the culprit.

**Puma config:**

It reproduces with the default configuration.

**To Reproduce**

Mentioned above.

**Expected behavior**

Requests shouldn't get discarded and 5xx errors should occur. On graceful shutdown, Puma should stop accepting new requests and wait until the ongoing ones finish.

**Desktop (please complete the following information):**
 - OS: Alpine 3.11 in Docker, ran in Kubernetes
 - Puma Version: 4.3.5

**Comment by cjlarose** [comment]
I'm putting together a PR for #2337 and I can confirm that puma doesn't quite handle all connections it accepts before it shuts down. We're working on a fix, but in the meantime, I think that in your specific case, you can mitigate the impact by introducing a short `sleep` in your pods' `preStop` lifecycle hook.

This blog post describes the technique: https://blog.gruntwork.io/delaying-shutdown-to-wait-for-pod-deletion-propagation-445f779a8304

The sleep with make it so that any kubernetes `Service`s that you have pointing to the pods in the deployment will have time to de-register the pod that's about to be killed. In the meantime, `puma` can process the requests it has in flight.

Clearly, this isn't the best long-term solution, but just thought I should offer it as a workaround while we're working on a more robust fix.

**Comment by volodymyr-mykhailyk** [comment]
@linkyndy We experiencing a very similar issue and now experimenting with different ingress/puma configurations to mitigate this

How is your k8s setup looks like? How are requests go to the server (ingress, load balancer)? What kind of requests you see fail? GET, POST, etc

**Comment by linkyndy** [comment]
@volodymyr-mykhailyk, requests go to nginx ingresses via ELBs. It's mostly GET requests, but that's not very relevant, since most of the requests that hit this service are GETs.

**Comment by zarqman** [comment]
we've had some success with a similar, but simplified version of what's in the blog post above mentioned by @cjlarose. in fact, we started with roughly the same (sleep + trigger quit/term), but sleep alone is more effective for us. we still see the rare 5xx when cycling pods, so this isn't quite there yet, but it's the closest we've gotten to date, and that's before tweaking the puma config (which is the next thing i'm looking at).

here's what's in our pod spec:
```
lifecycle:
  preStop:
    exec:
      command:
      - sleep
      - '15'
```
we run rails with a sidecar (to deliver /public) and use the same preStop in both.

@linkyndy, since you're running mostly GETs anyway, it may also be helpful to configure your nginx ingress to retry GETs on 5xx errors (if you haven't already). you'll still see the log messages, but it will retry on another pod and thus cover over the error for the end-user.

**Comment by linkyndy** [comment]
Thanks @zarqman for your insights! We've tried nginx retrying failed requests, but then moved to:

```
lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 5"]
```

which solved the vast majority of our failures (very few out of 10ks fail), which is acceptable for now.

**Comment by cjlarose** [comment]
@nateberkopec How do you feel about adding documentation for recommendations on how to configure puma when running in kubernetes?

**Comment by nateberkopec** [comment]
Hell yea! `kubernetes.md` would be great.

**Comment by avlazarov** [comment]
Same issue here with the ELB. The proper way to gracefully stop an HTTP backend (Puma) is to de-register its instance from the load balancer (or target group, depending of the balancer type) so no new requests are going to be send to that backend. With K8s however, there are multiple pods behind a target EC2, so a graceful shutdown is quite impossible with that setup, 5xx will pop.

I don't see what Puma can do as new requests are going to arrive via already established long-lived TCP connections even after a shutdown event has been received, you can't simply "stop accepting new requests" as those will yield to an HTTP error that the LB will not automagically retry for you. One solution is to have a service mesh that is aware of the K8s cluster world and can properly de-register pods, but that's outside Puma's realm.

**Comment by WJWH** [comment]
Hey @linkyndy, long time no see. :slightly_smiling_face: 

[This article](https://medium.com/flant-com/kubernetes-graceful-shutdown-nginx-php-fpm-d5ab266963c2) and also [this one](https://philpearl.github.io/post/k8s_ingress/) has a nice explanation of this type of thing. In particular, removing the pod from the "valid endpoint" list of the Service happens concurrently (!) with sending SIGTERM to the pod, so there is a small window where nginx thinks the pod is still good but Puma is already shutting down. The sleep gives the ingress some time to update its configuration and requests to drain. The proposed solution in the articles seems reasonable:
- (optional) Set `terminationGracePeriodSeconds` to something lower than the default 30 seconds.
- (optional) Set the `Connection: close` HTTP header to be doubly-extra sure no connections remain.
- Set the sleep in the preStop hook to be equal to `terminationGracePeriodSeconds` so that SIGTERM is effectively skipped and k8s will go immediately to SIGKILL. This gives the ingress up to `terminationGracePeriodSeconds` seconds to get its stuff sorted out and so the Puma server _should_ be idle by that time. (If it's the service I think it is (SU) then 10-15 secs should be fine) This does make the deploy a little bit longer but 15 seconds is usually not terrible.       

Btw this seems to be more a Kubernetes bug than a Puma issue, but some documentation would of course not hurt to inform users about gotchas like this.

**Comment by nateberkopec** [comment]
Relabeling as "docs" if someone wants to take a stab.

**Comment by WJWH** [comment]
I took a stab in #2515.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I found a nicer way now with checking how many open connections are still there:

```yaml
# deployment.yml
      containers:
        - name: mycontainer
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "/bin/check_open_puma_connections_before_termination.sh  > /proc/1/fd/1"]
```

```ruby
#!/bin/bash

PUMA_PORT=3000
MAX_RETRIES=30

# Function to get the number of established connections
get_connection_count() {
  netstat -an | grep ":$PUMA_PORT" | grep ESTABLISHED | wc -l
}

# Retry loop
for ((i=1; i<=MAX_RETRIES; i++)); do
  connection_count=$(get_connection_count)

  if [ "$connection_count" -eq 0 ]; then
    echo "$(date): No open connections. Safe to stop Puma."
    exit 0
  else
    echo "$(date): There are still $connection_count open connections. Sleeping..."
    sleep 1
  fi
done

echo "$(date): Max retries reached. Proceeding to stop Puma."
exit 0
```

Chmod +x this and copy it to your docker container, and it will wait with termination (for max. 30 seconds) as long as there are open connections. You need to have netstat included in your docker container (apt get install net-tools).

**Comment by wyardley** [comment]
> (optional) Set terminationGracePeriodSeconds to something lower than the default 30 seconds.

Sorry for bumping an ancient thread. I've read the docs and tried to follow them properly.

Would that be combined with the sleep as well? [This post](https://www.godaddy.com/resources/news/running-puma-in-aws) seems to suggest the opposite - that is, setting `terminationGracePeriod` to the 30s for Puma's shutdown window _plus_ the sleep time in `preStop` (currently 15s). Currently, I am keeping the default 30s `terminationGracePeriod`, and have added a 15s sleep; also fixed a problem where Puma had been started by a shell script so hadn't been catching the `SIGTERM` for graceful shutdown properly, but I'm still seeing 502s with `failed_to_pick_backend` listed as the reason in our GCP LB.

I'm also curious whether it's important to have the healthcheck on a different port? That's the approach that [lightship](https://github.com/gajus/lightship) (for node) and [kubernetes-health](https://rubygems.org/gems/kubernetes-health/) take. Otherwise, I feel like it's possible that the ingress and / or Kubernetes might think the pod is unhealthy too soon?

**Comment by zarqman** [comment]
@wyardley, still using a `preStop` with `sleep 15` here. We're using traefik and 15s is more than enough for it to withdraw the pod from the list of available endpoints and to finish up any ongoing requests. 

Our `terminationGracePeriodSeconds` is `60`, which probably longer than needed, but that's only a fallback if Puma fails to shutdown on its own.

We run Puma healthchecks on the same port as everything else and it's never been a problem. k8s already knows it's shutting down the pod, so it shouldn't be a problem. No need to overcomplicate it. 😄 

Have you changed Puma's `persistent_timeout` or is it still the default (which is just 20s)? And what's your GCP LB's keepalive timeout? You need GCP keepalive < Puma persistent_timeout.

**Comment by wyardley** [comment]
Thanks! This is all super helpful, and appreciate the response.

> And what's your GCP LB's keepalive timeout? You need GCP keepalive < Puma persistent_timeout.

Looks like we have the default for Puma's; there's a `timeout` setting in the `backendConfig` resource (which is 40s), as well as `drainingTimeoutSec` set to 60s.

https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#create_backendconfig is helpful, maybe I need to either reduce `drainingTimeoutSec` (though maybe NEGs need that long), or increase the `preStop` and `terminationGracePeriodSeconds more.

I think a bunch of things need to be set longer than I'd have hoped / expected because of the latency to deregister NEG endpoints, which according to the docs is [longer than I'd thought](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#500-series-errors) / remembered.

So, hopefully just a longer sleep in the `preStop` hook and a longer `terminationGracePeriodSeconds` will help 🤞

**Comment by wyardley** [comment]
I'm now at
Puma persistent_timeout: default (`20`)

In GCP BackendConfig:
`timeoutSec`: `40`
`connectionDraining.drainingTimeoutSec`: `60`

In Kube deployment:
`lifecycle.preStop.exec.command`: `75`
`terminationGracePeriodSeconds`: `180`

Still seeing some 502s (mostly with either `failed_to_pick_backend` or `backend_timeout` as the reason) on deployments.

Most of our requests shouldn't take a super long time to drain, so I'm almost wondering if the draining time may be making things worse rather than better.

> We run Puma healthchecks on the same port as everything else and it's never been a problem. k8s already knows it's shutting down the pod, so it shouldn't be a problem.

Maybe this is a more cloud-platform-specific thing, but in GCP, the LB also hits the healthcheck endpoint, and in the case of Network Endpoint Groups (NEGs), does so directly to the pod's service range, vs. going through Kubernetes. So I guess my thinking was, if the healthcheck from Puma itself stops responding immediately, it could cause some unexpected behavior, but maybe you're right that I'm overthinking it.

The NEG deregistration bit (see link in previous comment) is also somewhat cloud-provider-specific. In my experience, I don't think it should really take that long (they mention 1 minute) under normal conditions.

**Comment by zarqman** [comment]
@wyardley I still think you may need to switch things around so GCP `timeoutSet` (now 40) < Puma `persistent_timeout` (now 20). That is, I'm suggesting to increase Puma's timeout to > 40, or to decrease GCP's timeout to < 20.

In essence, you're currently telling GCP that the backend connection should last at least 40s, but Puma is being told to drop them after 20s. I'd expect that to lead to the `backend_timeout` errors. You want the LB to timeout _before_ Puma. This can also affect normal operation, not just when cycling pods.

As to `failed_to_pick_backend`, how many k8s nodes are you running, how many pods for the Ruby app in question, and how have you configured your k8s deployment's `rollingUpdate` strategy?

**Comment by wyardley** [comment]
> I still think you may need to switch things around so GCP timeoutSet (now 40) < Puma persistent_timeout 

Thanks.
Yes, have dealt with this before on NodeJS too way back, but misread your earlier message. However, looking a bit more closely to find the keepalive timeouts vs. the request timeout, I think the `timeout` parameter for backendConfig is the timeout for individual requests.

This is a classic ALB / HTTP LB, so based on:
https://cloud.google.com/load-balancing/docs/https#http-keepalive-timeout
https://cloud.google.com/load-balancing/docs/https#timeouts_and_retries
though, I think the Client HTTP keepalive timeout is 610s and the Backend HTTP keepalive timeout is 600s.

So would the recommendation be to set Puma's `persistent_timeout` to 615s or so, and will that affect anything else (timeout for individual requests), or have any potential risks / negative effects?

> how many k8s nodes are you running, how many pods for the Ruby app in question

This is on autopilot, so # of nodes will vary, but min of 2 pods, max of 10 pods (via HPA), and while we're doing rolling updates, it's just with default settings (and no explicit disruption budget).

**Comment by wyardley** [comment]
FWIW, I updated the `persistent_timeout` for Puma to 620s; this does not seem to have resolved the issue.

*Edit:* Thanks for all the help. But looks like this turns out to be a GKE / Autopilot known issue, for which the existing workarounds only _partially_ resolve it -- see: https://github.com/kubernetes/ingress-gce/issues/1718

**Comment by mpenalozag** [comment]
@wyardley Hey! Sorry to open this conversation again. I'm curious about something you said. I have the same configuration as you, GCP Load Balancer with GKE Autopilot cluster and a puma webserver.

> This is on autopilot, so # of nodes will vary, but min of 2 pods, max of 10 pods (via HPA), and while we're doing rolling updates, it's just with default settings (and no explicit disruption budget).

Why are you not using disruption budget? Wouldn't this cause to be downtime for you when Autopilot has a scaling event on the nodes?

I was experiencing lots of this issues, made some changes on my configuration and saw a huge decrease on this errors. However, they sometimes do appear. Have you been able to solve this 100%?

**Comment by wyardley** [comment]
> Wouldn't this cause to be downtime for you when Autopilot has a scaling event on the nodes?

Not in my experience thus far (granted, I haven’t used Autopilot a lot, but I’ve had quite a bit of experience with GKE broadly).

In my limited understanding, I think PDBs are more intended for overriding defaults, useful or you need to configure the default behavior, but that the default behavior is still rolling deploys and waiting for new nodes to come up.

It does seem like there are some inherent limitations with NEGs and GKE LBs that can’t be 100% worked around even with the known / common workarounds.

**Comment by mpenalozag** [comment]
@wyardley Thank you for your response. As of right now, roughly 0,006823% of my requests in the last 12 hours are hitting this 502. I'm not sure if this is expected or if there is anything else I could do to mitigate the issue. Maybe this kind of errors is expected within GCP SLAs? I'm not sure anymore if this is an issue with Kubernetes deployments configurations. What do you think?
