### ISSUE TITLE
Improved documentation on startup options

### ISSUE THREAD

**Issue by ryanwi** [puma/puma#2459]
**Is your feature request related to a problem? Please describe.**
There are many ways to start puma across both Rails and Sinatra apps. It can be confusing and frustrating trying to come up with a good solution that is consistent across applications and  consistent with community best practices.

On Rails, should you start with `$ puma -C config/puma.rb` or `$ rails s`?  I think it's clear because the README nicely states the following:

> It is recommended that you use Puma's executable instead.

But, On Sinatra, when you ask the question if you should start with `$ puma -C config/puma.rb` or `$ ruby app.rb -s Puma` or `rackup` the answer is not as clear.

From what I've experienced upgrading a dozen or more Rails and Sinatra apps to run on Docker/Kubernetes, it feels like starting with `bundle exec puma -C config/puma.rb` across both platforms is the more consistent approach. It makes for a consistent startup be it Procfile, CMD in a Dockerfile, or bash/cli. Also, the puma config file becomes a consistent place to control Puma ports, env and threads. Yet the Puma README suggests starting on Sinatra with `$ ruby app.rb -s Puma`. Is that the preferred approach for Sinatra? If so, why? what are the benefits of starting an sinatra/puma app that way vs with `puma -C`? The downside appears to be having to put config for ports and such inside the sinatra configure blocks are on the command line.

**Describe the solution you'd like**
An ideal solution would update the README to be authoritative on how to start Sinatra apps.  If `$ ruby app.rb -s Puma` is the preferred, what makes it so?

**Describe alternatives you've considered**
I've read through Sinatra docs and Puma docs/issues/code and do not have a clear understanding yet.  For example, this 3 year old comment gives some context on using `$ ruby app.rb -s Puma`:

> Sinatra doesnt typically use rackup files (which is why the README says to use ruby app.rb -s Puma).
https://github.com/puma/puma/issues/1465#issuecomment-345719511

But, this comment then calls out starting puma directly

> You should be using bundle exec puma, not bundle exec rackup.
https://github.com/puma/puma/issues/13#issuecomment-316473258

**Additional context**
I understand there are many options and choices and trade-offs for all. With many devs coming to Puma through Rails, having strong conventions can be helpful to onboard.

**Comment by nateberkopec** [comment]
The comment you linked does provide the necessary context:

> Sinatra doesnt typically use rackup files (which is why the README says to use ruby app.rb -s Puma)

Puma uses rackup files to start apps. Rails has `config.ru`, which, by convention, is the filename that Puma looks for in the present working directory if you do not specify a rackup file.

Sinatra apps typically do not use rackup files. So, Puma cannot mount them as a rack app. Instead, you let the Sinatra app file run (`ruby app.rb`) and provide a command line option _to Sinatra_ that tells them to mount the Sinatra rack app with Puma.

Puma is actually the default server for Sinatra nowadays, so you can just `ruby app.rb`.

There's nothing we can really do about this on the Puma side without heavily special-casing Sinatra, which I do not want to do. The fact that you can't start Sinatra with `puma` is a simple consequence of Sinatra's design choices. 

In order to configure Puma and use Sinatra, you must create a rackup file. This where my comment on #13 was wrong.

```ruby
#config.ru
require './app'
run Sinatra::Application
```

After you've done that, we can run Puma with `puma`. I'll update the docs to recommend this, because "use puma in a way that you can never configure it" is not convenient.

**Comment by ryanwi** [comment]
Thank you for clarifying and providing the missing context.  I believe my confusion was because the Sinatra apps that I was migrating already had a config.ru file present. I was not aware that it was more common for Sinatra apps to not have one.

**Comment by dentarg** [comment]
> I was not aware that it was more common for Sinatra apps to not have one.

Me neither, and I have been building Sinatra apps for ~10 years now, all with `config.ru` files 😆
