### ISSUE TITLE
Setting Up Control Server

### ISSUE THREAD

**Issue by ggennrich** [puma/puma#2532]
I'm trying to set up a Puma Control Server so that a third party service that has an agent on the same host can access statistics. Specifically, I want the DataDog agent to be able to check the stats for several puma instances running on a server. The control server should only be accessible on the localhost and not externally since the agent is already running on the same system. I have two questions around this.

- I've tried setting `activate_control_app` in `puma.rb` config to the following:

  `activate_control_app 'tcp://0.0.0.0:9293'`
  and I have set up the DataDog agent to look at that control URL. However, I keep getting connection errors 
  `Error: HTTPConnectionPool(host='0.0.0.0', port=9293): Max retries exceeded with url: /stats?token=XXXX (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe941a73310>: Failed to establish a new connection: [Errno 111] Connection refused'))`
- If I have several different applications running on an instance and I want DataDog to collect metrics for each of them do I set the control app URL to the same in each `puma.rb` config?

Appreciate any help here!

**Comment by cjlarose** [comment]
Since you mentioned that you want the control server to only be accessible from programs running on the same host, I'd recommend changing

```
activate_control_app 'tcp://0.0.0.0:9293'
```

to 

```
activate_control_app 'tcp://127.0.0.1:9293'
```

In the former configuration, `0.0.0.0` means to listen on _all_ addresses, including any public ones. In practice, if you have the appropriate firewalls set up elsewhere in the network, this isn't that big of an issue, but it's better practice to just listen on the interfaces you need so that you're not depending entirely on the external firewall for protection.

> `Error: HTTPConnectionPool(host='0.0.0.0', port=9293): Max retries exceeded with url: /stats?token=XXXX (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe941a73310>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Based on the error message, I think the client might be misconfigured. `0.0.0.0` is a special address that's used to indicate that the server wants to listen on all address, but I'm not really sure what it means for a client to _connect_ to `0.0.0.0`. I think in this case, you can change your client to connect to the host `localhost` or `127.0.0.1` instead of `0.0.0.0`.

> If I have several different applications running on an instance and I want DataDog to collect metrics for each of them do I set the control app URL to the same in each puma.rb config?

You'll need to configure each `puma.rb` file for each application to use `activate_control_app`, but you'll need to use a distinct port number for each one. For example, the first might be  'tcp://127.0.0.1:9293' and the next  'tcp://127.0.0.1:9294'. Otherwise,  you'll get port conflicts.

**Comment by dentarg** [comment]
I think what @cjlarose wrote answers this!

**Comment by ggennrich** [comment]
@cjlarose Thank you for the detailed explanation. This all makes perfect sense to me. I'm going to make those necessary changes and should I still have issues I will let you know.
