### ISSUE TITLE
Log warning when max worker count is 1

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2534]
I'm struggling to think of a good reason to use cluster w/1 worker vs single mode.

**Comment by MSP-Greg** [comment]
Yeah, that question has kept me up a few nights...

Maybe the real question is what benefit would there be using one worker instead of more?  If your platform has fork, two workers (or more) allows a phased-restart, etc?

**Comment by vizcay** [comment]
Hi @nateberkopec I've asked that specific question 4 years ago: https://github.com/puma/puma/issues/1426

**Comment by nateberkopec** [comment]
@vizcay indeed.

Will leave open for a while for comment if someone can provide a good reason.

**Comment by cjlarose** [comment]
FWIW I've found this "feature" to be useful in testing clusters. The [bundler preservation tests](https://github.com/puma/puma/blob/a2d38b12242dc1c4fca82b8e519baed9f63263f1/test/test_preserve_bundler_env.rb#L28) and [tests around gem changes in phased restarts](https://github.com/puma/puma/blob/a2d38b12242dc1c4fca82b8e519baed9f63263f1/test/test_worker_gem_independence.rb#L98) both use single-worker clusters.

So we want to keep the feature, but logging a warning message seems appropriate.

**Comment by cjlarose** [comment]
One potential use case I can think of is that a single-worker cluster might be more resilient to full application crashes. In a cluster, if the worker process exits because of an unexpected failure (segfault or something), the cluster will restart the worker.

In single-mode, it's all one process, so the whole process would die. Of course, users should be using a process manager anyway that'll restart the single-mode process. What users lose here is that the sockets would be unbound-and-rebound so they could lose new connections when the failover happens. In the single-worker cluster situation, the sockets would remain listening.

Still, printing a warning in this case probably wouldn't hurt users if they really wanted a single-worker cluster.

**Comment by vizcay** [comment]
> What users lose here is that the sockets would be unbound-and-rebound so they could lose new connections when the failover happens.

Is my understanding that by using a systemd socket and service binded the socket will queue requests while the service restarts.

> For most folks, it's not what they want.

Exactly, I was surprised first time with this behaviour.

**Comment by cjlarose** [comment]
> Is my understanding that by using a systemd socket and service binded the socket will queue requests while the service restarts.

That's true. If you happen to be using systemd's inherited sockets, you're good to go. But any other process manager might not have the same feature.

**Comment by CGA1123** [comment]
I think this is well worth a warning at least. I recently noticed that we were running 1 worker clusters in production for the majority of our applications.

Switching to single mode saved ~15% RAM across our applications, letting us increase the thread count or bringing us under the memory limitations of our servers and avoiding swapping! We switched over in Oct last year, and haven't noticed any adverse effects on our setup.

There are graphs and such attached on a [write-up](https://medium.com/@CGA1123/reducing-rails-memory-usage-by-15-56090b6294bd) I did about this.
