### ISSUE TITLE
Volatile queue timing in 5.3.x with low request volume

### ISSUE THREAD

**Issue by booleanbetrayal** [puma/puma#2634]
**Describe the bug**

We are seeing erratic latency from our nginx proxy into our Rack middleware via request header traces. This is occurring in a Kubernetes cluster where the load balanced Puma servers are severely under-saturated in terms of requests, generally only being hit by internal and external health check pings every minute or so. We see this erratic behavior with our consistent Puma config when updating from 5.2.2 to 5.3.1 / 5.3.2. The proxy times consistently revert when we revert back to 5.2.2. 

**Puma config:**

```
threads 4, 4
workers 6
wait_for_less_busy_worker

after_worker_boot do
    require 'prometheus_exporter/client'
    require 'prometheus_exporter/instrumentation'
    client = PrometheusExporter::Client.default
    client.custom_labels = { type: "puma_worker" }.merge({ pod: ENV["K8_POD_NAME"], ip: ENV["K8_NODE_IP"] })
    PrometheusExporter::Instrumentation::Puma.start(client: client)
end

before_fork do
    ActiveRecord::Base.connection_pool.disconnect!
end

on_worker_boot do
    ActiveRecord::Base.establish_connection
end

fork_worker
```

**To Reproduce**

Will try to synthesize a simple test soon, but this result is from a trickle of automated health-check endpoint requests in which the controller makes a connection to our DB and Cache servers. Upgrading from 5.2.2 produces the volatile queue timing. Downgrading again consistently lowers queue time:

<img width="901" alt="Screen Shot 2021-05-24 at 8 54 40 PM" src="https://user-images.githubusercontent.com/981825/119433366-54195600-bcd3-11eb-8c82-2eb62500645a.png">

We DO NOT see this volatile behavior under situations where the request volume is higher and less erratic. Queue time remains consistently low in that scenario.

**Expected behavior**

Proxy times in under-saturated request scenarios remain consistently low.

**Desktop (please complete the following information):**

 - OS: Alpine Linux 3.13
 - Ruby 2.7.2
 - Puma: 5.3.x

**Comment by nateberkopec** [comment]
There will probably be very, very significant differences here between 5.3.0, 5.3.1, and 5.3.2. Personally, I'd like to see a queue time graph from `5.3.2`.

What version of Rails are you using? You probably can delete this from your config:

```ruby 
before_fork do
    ActiveRecord::Base.connection_pool.disconnect!
end

on_worker_boot do
    ActiveRecord::Base.establish_connection
end
```

**Comment by booleanbetrayal** [comment]
Hi @nateberkopec - The above graph shows the queue timing transition from `5.3.2` to `5.2.2`. We are on Rails `6.1.3.2`.

**Comment by nateberkopec** [comment]
cc @wjordan 

Please note that 5.2.2 has security vulnerabilities. It may be worth trying `5.3.1`.

**Comment by booleanbetrayal** [comment]
We saw similar behavior from `5.3.1` and are back on `5.3.2` as it is not adversely affecting normal traffic scenarios.

**Comment by nateberkopec** [comment]
@booleanbetrayal Was that a typo? I'm unclear on what versions are affected:

* ✅ `5.2.2` and previous
* ❓ `5.3.0`
* ❓ `5.3.1`
* ❓ `5.3.2`

**Comment by wjordan** [comment]
@nateberkopec if I understand, they observed issues in both 5.3.1 and 5.3.2 but only in low-traffic scenarios, so they can still run on 5.3.2 since the issue doesn't impact their normal workload.

**Comment by booleanbetrayal** [comment]
@nateberkopec / @wjordan - I'm a little time-constrained atm, so have not been able to bisect hunt, but I was able to deploy a revert to `5.3.0` and observe the same phenomenon, so it seems to be introduced somewhere in that commit batch. 

Toggling off `wait_for_less_busy_worker` and `fork_worker` (favoring `preload_app!` instead), both independently and collectively, did not seem to make an impact in reducing the high queue times under low load.

**Comment by nateberkopec** [comment]
Ok so what I'm getting is:

* ✅ `5.2.2` and previous
* 🔴  `5.3.0`
* 🔴  `5.3.1`
* 🟡  `5.3.2`

**Comment by booleanbetrayal** [comment]
@nateberkopec - All the `5.3.x` variants behave consistently, from what I've observed. 

It's just that these all run fine under normal workloads, and with `5.3.2` being the latest and greatest, and includes the latest security patch, we're on that.

**Comment by wjordan** [comment]
I don't see anything [between 5.2.2 and 5.3.0](https://github.com/puma/puma/compare/v5.2.2...v5.3.0) that jumps out as a likely cause of this issue. I think the next step would be to run the bisect or put together a test case we can reproduce ourselves if/when you have the time to continue debugging this.

**Comment by booleanbetrayal** [comment]
Thanks @wjordan . Will try to carve out the time!

**Comment by brandonhilkert** [comment]
I think we may be seeing something similar. Two weeks ago we upgraded from `5.2.0` to `5.3.2`. We since saw response times sporadically rise without much explanation. I assumed it was due to application changes. We reverted most all application code for periods of time and still saw issues. 

Our issues manifested themselves as really high CPU usage. We run on AWS ECS under Fargate (`1.4.0`). Here's our puma config for the containers:

```
workers Integer(ENV["WEB_CONCURRENCY"] || 2)
threads_count = Integer(ENV.fetch("RAILS_MAX_THREADS") { 5 })
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

if ENV['RACK_ENV'] == 'production'
  bind        "unix:///bark/tmp/sockets/puma.sock"
  pidfile     "/bark/tmp/pids/puma.pid"
  state_path  "/bark/tmp/pids/puma.state"
end
```

Our response time is typically < 200ms. We'd see response times start to rise and it occurred to me after some period of time that this was due to single containers showing really slow responses, so the overall average would be dragged down. When I noticed this, I was able to isolate it to single containers and their behavior:

<img width="1095" alt="Screen Shot 2021-06-13 at 6 31 04 PM" src="https://user-images.githubusercontent.com/744212/121906377-ebc10180-ccdf-11eb-817e-edc84b778f17.png">

As you notice, response times went from < 200 ms to 5-8 sec. When I looked at the transactions post-issue, everything takes longer. It's like every part of the response was multiplied by 10. 

On the AWS side, I'd see avg. CPU for the service go way up without any related change in total number of requests:

<img width="1491" alt="Screen Shot 2021-06-11 at 10 40 39 AM" src="https://user-images.githubusercontent.com/744212/121906712-3c385f00-cce0-11eb-88b9-c66ce3fbaeae.png">

Deploying new containers to the service immediately resolves the issue:

<img width="972" alt="Screen Shot 2021-06-07 at 4 23 23 PM" src="https://user-images.githubusercontent.com/744212/121907219-b4068980-cce0-11eb-9ed0-f086d3516d22.png">

After some period of time (typically within a few hours), almost all of the 6 containers seem CPU-pinned, which prompts the service to auto-scale (we trigger it based on a CPU alarm of 50+% for overall service CPU usage). It'll auto-scale until it reaches the max container. We typically deploy 5-10 times per day so I think we were covering the problems throughout most of the day (new containers always resolved it).

I stumbled on this thread, which led me to revert the upgrade. We're back at `5.2.0` and while it hasn't yet been 24 hours, we typically saw the behavior within that range, especially the start of a week like today (Monday AM).

Happy to help provide data where it makes sense.

**Comment by wjordan** [comment]
@brandonhilkert your issue sounds different from the original issue description, where it was mentioned "We DO NOT see this volatile behavior under situations where the request volume is higher and less erratic. Queue time remains consistently low in that scenario."

In any case, if you are able to collect more data on the issue, the details I asked for in https://github.com/puma/puma/issues/2634#issuecomment-848063139 would be helpful:

- Isolate the issue to a simple test, and provide all source code and steps necessary for others to reproduce the issue
- Try out 5.3.0 at least (to narrow down the specific version change triggering your issue), or if you're able to quickly test individual commits a [git bisect](https://git-scm.com/docs/git-bisect) would be even more helpful

Beyond that, for a CPU utilization spike the next step would be to run a profiler like [`rbspy`](https://github.com/rbspy/rbspy) to determine exactly what lines of code are hogging the CPU when the issue is occurring. (Though you said it's _probably not_ your application code, sounds like you haven't definitively ruled that out yet)

**Comment by brandonhilkert** [comment]
@wjordan Happy to open a separate issue if you're prefer. We'll try `5.2.2` to `5.3.0` and see if we can recreate.

**Comment by brandonhilkert** [comment]
After some version experiments on our side, I've ruled out it being a change in Puma. Sorry for any confusion it caused.

**Comment by nateberkopec** [comment]
(I was too eager with the close - forgot that OP was a different issue)

**Comment by nateberkopec** [comment]
Closing, as I'm not sure this is an issue in Puma. If someone can repro with an example app we can reopen and take a look.
