### ISSUE TITLE
[Documentation] How to best tune Puma for Kubernetes 

### ISSUE THREAD

**Issue by arianf** [puma/puma#2645]
Current documentation here is a bit lacking: https://github.com/puma/puma/blob/master/docs/kubernetes.md

What is the best practice for running puma within a Kubernetes pod? Do you want a high amount of workers per pod? Low amount of workers per pod? Or no worker per pod?

Example 1: 2 pods, with 50 workers
Example 2: 25 pods, with 4 workers
Example 3: 100 pods, with no workers

Or are the differences between these configurations negligible?

I guess my basic question is how do you get the most out of your Kube resource quota with Puma?

Secondly how do you determine how much Kube resources to give a pod, is there a way to tell if puma is resource constrained? Like how much request vs limit resource to give.

**Comment by nateberkopec** [comment]
Agreed, I would be probably be the one to write this.

Fast answer in case this decision is blocking you:

1. Worker counts should be somewhere between 4 and 32 in most cases. You want more than 4 in order to minimize time spent queueing for a free Puma worker, but probably less than ~32 because otherwise autoscaling is working in too large of an increment.
2. If multithreaded, assign 1 CPU per worker. If single threaded, assign 0.75 cpus per worker.
3. Most Pumas will use about ~512MB-1GB per worker. However, you probably shouldn't bother with setting limits lower than like 2GB per process, because most places you are deploying will have 2GB of RAM per CPU.

**Comment by gottfrois** [comment]
@nateberkopec thanks for the quick summary. Is there a reason for assigning .75 cpus instead of 1 for single threaded workers?

Just adding here that we use the `plugin :statsd` from https://github.com/yob/puma-plugin-statsd to monitor the `puma.backlog` metric and see whether request queuing gets out of control.

**Comment by nateberkopec** [comment]
Basically a single threaded worker will have long-run CPU utilization of (`1 - percent_of_time_waiting_on_io`). Most webapps wait on I/O about ~25% of the time, so in order to use all available CPU, you need extra workers.

**Comment by johnnyshields** [comment]
@gottfrois my two cents, err on the side of fewer pods with as many threads/processes as you can.

Something like 4 pods w/ 16 cores each, 16 processes each, each process running 20 threads sounds about what we're doing.

Total threads (pods * processes * threads) is what you want to maximize to handle more concurrent requests. From there, since Puma 5 has CoW memory optimizations it's better to run more processes on few pods as you'll reduce the total amount of RAM you're using. Something like 1 process per CPU core is probably right but your mileage may vary.

**Comment by nateberkopec** [comment]
@johnnyshields IME more than 5 threads is usually too much for a webapp (which is why 5 is now the default for Puma on MRI). Over that amount, the GVL is locked >80% of the time but with extra free threads, Puma processes will continue to pick up new requests, which they cannot immediately service, leading to increased latency for no throughput gain.

**Comment by johnnyshields** [comment]
Hmmm... I don't have detailed data on this anymore but when we upped the thread count to around 20 it greatly increased the health of our k8s pods. The main problem we were fighting against were the k8s healthchecks...

**Comment by vfiset** [comment]
@nateberkopec when running in worker mode, if a worker gets OOMkill by the kernel, kubernetes won't be aware of that and it will go pass monitoring, that's something to take in consideration IMO.

**Comment by brunoarueira** [comment]
@vfiset Maybe define a http health check and the kubernetes will heal the container based on that.

**Comment by vfiset** [comment]
@brunoarueira health check would help here since if one of the n worker gets OOMkilled, any of the other could respond to the health check request.

**Comment by johnnyshields** [comment]
@vfiset are you sure that's the case? I though Puma's IPC would track child status and spin up a new child if needed. Can you make a test that demonstrates this?

**Comment by vfiset** [comment]
@johnnyshields puma IPC will spin another one, no doubt, but the killed process by the kernel will fly under k8s radar.

**Comment by nateberkopec** [comment]
OK, [I finally have folded this into official documentation](https://github.com/puma/puma/commit/9282a8efa5a0c48e39c60d22ca70051a25df9f55)! If you have more questions, ask in this thread and I'll add to the docs.

**Comment by Rudy-Zidan** [comment]
@nateberkopec we were trying to configure puma workers and threads and found the Kubernetes guide specifically "Pods section and puma configuration".
Our puma runs in a cluster mode once we followed 4 processes and 4 Cpus (i understand that every worker needs 1 cpu core for better utilization), however i don't understand why it should be at least 4 workers per pod, can you help me understand why?

**Comment by nateberkopec** [comment]
In any queueing system, queue time is proportional to 1/n, where n is the number of things pulling from the queue.

Each pod will have its own request queue (i.e., the socket backlog).

If you have 4 pods with 1 worker each (4 request queues), wait times are, proportionally, about 4 times higher than if you had 1 pod with 4 workers (1 request queue).

**Comment by h0jeZvgoxFepBQ2C** [comment]
Could you also add an example puma.rb with sane defaults for kubernetes? Would be nice to see a "recommended" configuration?

**Comment by nateberkopec** [comment]
For anyone interested in that - help me out, what exactly would you want to see? `deployment.yaml` - ok noted, what else? i.e. what files in your k8s deployment should we provide a generic/docs version of?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Actually i only have a deployment.yaml and a puma config file.

It would be just nice to get some nice, performance fine tuned settings for kubernetes + nginx ingress controller (in our case), since I'm too newb to really understand what are the best worker/thread combinations... Right now we have it running with following env variables, only one worker per pod:

```yaml
            - name: PUMA_MAX_THREADS
              value: "5" # max is 10
            - name: MALLOC_ARENA_MAX
              value: "2"
```

**Comment by Ruto8** [comment]
Hello there,

My team and I've been looking into health checks specifically, and we had an issue with our Puma setup. I see it mentioned several times in this issue but without a recommendation. While looking online at how to set up a good health check (for k8s or not) with Puma, the most common version I found was returning 200 from an endpoint of your app. It makes sense; it worked for us for years. The app was ready when it was ready to reply.

Unfortunately for us, once we started to take a closer look, it didn't work too well. We started implementing all recommendations from the Puma for Kubernetes guides. And we started noticing latency spikes during deployments (sometimes even 503s). 

A regular setup at our company is using 4 Puma workers. We commonly reply to a readiness check when only 1 of those four workers is booted. Once this happens, we push traffic towards that pod. That pod cannot receive as many requests as we predicted because it only uses 25% of workers. This ends up in requests being queued and, therefore, latency.

We then proceeded with implementing a custom Puma plugin that runs a health check server that checks Puma stats for booted workers. If booted workers are equal to the number of workers from config - we're good. This solved all the problems for us, and we have a stable deployment now.

Below you can find a part of code that does that for us. We're considering open-sourcing this as a gem, but I'll admit - I'm no Puma expert. It would be good to hear from someone if this strategy makes sense. 

(PS. It would be probably easier to do that if we could access Puma stats from a worker, which we cannot today)

```ruby
require "webrick"

class HealthCheckServer
  attr_accessor :server, :launcher, :thread

  def initialize(launcher:, port: 9393)
    @launcher = launcher
    @server = WEBrick::HTTPServer.new(Port: port)
    expected_workers = @launcher.options[:workers] || 0

    @server.mount_proc "/checks/_readiness" do |req, res|
      booted_workers = @launcher.stats[:booted_workers]
      res.status = (booted_workers == expected_workers) ? 200 : 503
      res.body = "{}"
    end

    @server.mount_proc "/checks/_liveness" do |req, res|
      res.status = 200
      res.body = "{}"
    end
  end

  def start
    @thread = Thread.new { @server.start }
  end

  def stop
    @server.shutdown
    @thread&.join
  end
end

Puma::Plugin.create do
  def start(launcher)
    health_check_server = HealthCheckServer.new(launcher: launcher)
    health_check_server.start

    launcher.events.register(:state) do |state|
      if %i[halt restart stop].include?(state)
        health_check_server.stop
      end
    end
  end
end
```

Below you can see a screenshot from our metrics to see a difference between deployments that report ready from a Rails endpoint vs using the above code extracted into a gem.
![image](https://github.com/user-attachments/assets/58f22d51-5210-4d75-ae9e-688585025435)

**Comment by Tensho** [comment]
> A regular setup at our company is using 4 Puma workers. We commonly reply to a readiness check when only 1 of those four workers is booted. Once this happens, we push traffic towards that pod. That pod cannot receive as many requests as we predicted because it only uses 25% of workers. This ends up in requests being queued and, therefore, latency.

@Ruto8 I believe you have "app preload" disabled, otherwise all workers have to be ready to serve healthcheck requests 🤔 What is your use case? 

Nonetheless, plugin serving healthchecks seems like a great idea as it doesn't share the same socket backlog with workers, hence healthchecks are independent from end user requests. I have a similar problem with failing healthchecks when all pod workers/threads are busy under the high load. I wonder is it a recommended way to deal with healthcheck in Kube world – independent web server?

![Image](https://github.com/user-attachments/assets/c2ce2bf4-c4f6-4200-a5af-736994deba88)
