### ISSUE TITLE
Recycling workers (without fork_worker)

### ISSUE THREAD

**Issue by Roguelazer** [puma/puma#2659]
**Is your feature request related to a problem? Please describe.**
My big Ruby app leaks memory the longer it runs but does some non-forksafe stuff at startup so cannot be preloaded.

**Describe the solution you'd like**
I would like to recycle workers after some number of requests, similar to Apache's [`MaxConnectionsPerChild`](http://httpd.apache.org/docs/current/mod/mpm_common.html#maxconnectionsperchild), uwsgi's [`max-requests`](https://uwsgi-docs.readthedocs.io/en/latest/Options.html?highlight=%22max-requests%22#max-requests), uvicorn's `--limit-max-requests`, and similar. Ideally this would have a small amount of random splay (similar to uwsgi's `max-requests-delta`) to minimize thundering herds.

As far as I can tell, this is currently only supported in `fork_worker` mode, which requires that your application be forksafe and not do anything untoward such as initialize threads at global scope at import time.

**Describe alternatives you've considered**
I believe I can do this myself with a `puma.rb` like the following:

```
on_worker_boot do
  $requests_since_recycle = 0
  $recycle_after = (1000 * (0.85 + rand * 0.3)).to_i
  $sent_signal = false
end

out_of_band do
  $requests_since_recycle += 1
  if $requests_since_recycle >= $recycle_after && !$sent_signal
    $sent_signal = true
    Process.kill("TERM", Process.pid)
  end
end
```

This only works if the server is idle enough that `out_of_band` gets called after every request, though, which it probably doesn't in the real world. I don't think there's any hooks that are guaranteed to get called once per request.

I could probably make a Rack middleware that increments `$requests_since_recycle`, but sharing a global variable between modules seems in poor taste.

**Comment by cjlarose** [comment]
One option is to use [`puma_worker_killer`](https://github.com/schneems/puma_worker_killer). That periodically kill workers based on time, not on the number of requests, though.

`puma_worker_killer` works by starting a new thread in `before_fork`, so it doesn't depend on `out_of_band` having to be called. I think you could implement something similar for your purposes, using `Puma.stats_hash` to figure out how many requests each worker has served. For any worker above the threshold, you can kill them.

**Comment by cjlarose** [comment]
I'm also open to a new configuration option for Puma that would enable this functionality. Clearly, the hooks are already in place to be able to kill workers after a given number of requests since `fork_worker` does this already. Seems natural to enable this functionality even if you're not using `fork_worker`.

This could be an excellent alternative to `puma_worker_killer` for folks that don't need the full functionality of that gem.

**Comment by nateberkopec** [comment]
I think this is better suited to `puma_worker_killer`. There's too many finer points to killing workers that the gem already takes care of, and we currently do very little worker killing in `puma` itself. The "division of responsibilities" seems very clear right now and adding this feature to `puma` core would muddy the waters.

**Comment by cjlarose** [comment]
I actually disagree here. `puma_worker_killer` AFAIK pretty blindly just sends `kill` signals to the individual worker processes, without taking into account how many workers are still up and able to service requests. Implementing the feature in puma itself, which I think largely already exists, gives us the opportunity to more gracefully phase out workers (one at a time, ensuring we don't drop below `workers - 1` total workers available).

**Comment by sitano** [comment]
For me the problem with the `puma_worker_killer` is that it does a rolling restart of all the workers with randomized start point instead of making all of the workers independently restart in randomized time intervals. Let's say this can be patched inside of the `puma_worker_killer`.

But there is another problem. The workers respawn timeout cap. IDK if it is somehow changed in the new versions but in 4.3.12 the respawn checker has a timeout in 5 seconds to test if there are exited workers to respawn which is too bad for our use case. We need it to respawn them instantly.

I am curious (? @nateberkopec) if it is a known problem in the Puma community and if is it addressed somehow?

I have developed a workaround patch for myself and I will be glad if it will make it to the main repo but not sure how people are solving it themselves. Maybe I am missing something.

**Comment by sitano** [comment]
I have found the answer to my question. It's a race condition in 4.x. Fixed since 5.0 by https://github.com/puma/puma/commit/67f9b1f3f2318c14279ba212ebdfaa5bccd9bc08.

**Comment by nateberkopec** [comment]
As of Puma 5.0, Puma.stats now has an incrementing request count. This could be used by `puma-worker-killer` (or any other tool) to kill workers after `x` number of requests. So, since this feature can now be implemented by external tools, I'm closing this issue.

**Comment by dfuentes77** [comment]
I'm noticing that [puma_worker_killer](https://github.com/schneems/puma_worker_killer) doesn't seem to be maintained.  I fear if there is a major development with puma related to `fork_worker` that puma_worker_killer isn't compatible, users would be stuck with not being able to use both.  I can't seem to find any supported alternative.  Feel free to point out where I should post this or if there is another tool that does that same and seems to be maintained.  Thanks!

**Comment by sherifabdlnaby** [comment]
This should have been a natively supported feature.
