### ISSUE TITLE
Logging of received signals

### ISSUE THREAD

**Issue by firefart** [puma/puma#2701]
Hi,
we currently investigate why our workers get restarted in a kubernetes cluster and I noticed puma only logs the boot messages like so 
```
[1] - Worker 0 (PID: 10) booted in 0.1s, phase: 0
[1] - Worker 1 (PID: 17) booted in 0.1s, phase: 0
[1] - Worker 2 (PID: 25) booted in 0.01s, phase: 0
[1] - Worker 3 (PID: 33) booted in 0.0s, phase: 0
```

Is there a way to log the receive of all handled signals documented here https://github.com/puma/puma/blob/master/docs/signals.md to the log? This would help in troubleshooting to see which signals where sent to puma.

**Comment by nateberkopec** [comment]
I think you can have multiple Signal handlers, right?

Just drop:

```ruby
%w[kill int].each do { |s| Signal.trap(s, some_stuff_to_log) }
```

into your app somewhere?

**Comment by jjb** [comment]
that code will replace the puma signal handler. here's how to add signal handler behavior while preserving existing behavior: https://github.com/mperham/sidekiq/pull/4991

in the sidekiq case, initializer code runs before the sidekiq handler is defined, so that PR is necessary to allow users to augment the signal handlers. im not sure if puma's signal handlers get defined after rails initializers.
