### ISSUE TITLE
Get current running requests details

### ISSUE THREAD

**Issue by alain-andre** [puma/puma#2837]
We want to move from Passenger to Puma but one point is blocking us : we cannot get the current running requests details like `passenger-status  --show=requests` does.

Is there any solution to get this kind of information ? It is really important for us to know the request and the memory used as well as the time it is running.

**Comment by nateberkopec** [comment]
> current running requests details
> time it is running

I took a look at the stats provided. I think you could accomplish this with a Rack middleware - I'm not sure any exists already that does this, using the Rack environment for its information?

> memory used

Unfortunately, providing information beyond what `ps` does is not possible in a multithreaded MRI Ruby process. There is no API (and I'm not sure one could be built) for attributing memory use to individual threads. Since `ps` and other tools can measure the memory usage of Puma, I don't see a reason for us to add it.
