### ISSUE TITLE
Confusion on how to configure nakayoshi_fork option on a project with nakayoshi_fork gem

### ISSUE THREAD

**Issue by mtoygar** [puma/puma#2898]
**Describe the bug**

This is actually not a bug but a confusion I have while configuring Puma. Does enabling `nakayoshi_fork` Puma config in a project where [nakayoshi_fork](https://github.com/ko1/nakayoshi_fork) is already a dependency cause GC to run ~8 times(4 by Puma, ~4 by nakayoshi_fork monkey_patch) before forking? In that case should I disable `nakayoshi_fork` option as the monkey patch already does that and run `GC.compact` manually in the `before_fork` callback? If that is the case, would it be reasonable to split these two CoW optimizations into 2 separate configs?

Thanks for the great work you are doing 🙇

**Comment by nateberkopec** [comment]
If you're using the Puma nakayoshi_fork option, there's no reason to use the gem (unless you're forking somewhere else in your app, in which case the approaches are incomptaible).

We're removing the option in Puma 6 because it did not create any big gains, so I hope this answers your question. We won't be changing the behavior of this feature because it's on the way out.
