### ISSUE TITLE
Sinatra streaming broken in Puma 6.0.0

### ISSUE THREAD

**Issue by dentarg** [puma/puma#3000]
See https://github.com/sinatra/sinatra/issues/1832 for more details but this simple app https://github.com/sinatra/sinatra/blob/v3.0.2/examples/stream.ru works fine with Puma 5.6.5 but with 6.0.0 it waits until all `sleep`s have finished before the response is returned (this is more noticeable if you increase the sleep time in the example).

As noted in https://github.com/sinatra/sinatra/issues/1832#issuecomment-1291175026 the example runs as expected in falcon (v0.42.3).

**Comment by dentarg** [comment]
If I change `IO_BUFFER_LEN_MAX` to a low value like `1` the streaming works

https://github.com/puma/puma/blob/8159aa4a7783cd1f4bdb75e918dad6ff2492bac7/lib/puma/request.rb#L24-L25

Used here 

https://github.com/puma/puma/blob/03ed6c8e78b9ba0c76055af2ddb0bdd532807d6c/lib/puma/request.rb#L303-L325

The buffering was introduced in https://github.com/puma/puma/pull/2896

**Comment by MSP-Greg** [comment]
What about something like 64kB?

**Comment by dentarg** [comment]
Sure, it would probably help many cases. What about making it configurable? Is that a good idea?

I suspect a more reliable solution for Sinatra is to switch to the new Streaming body  https://github.com/puma/puma/pull/2740, that wouldn’t be buffered, or? Need to try this myself

**Comment by MSP-Greg** [comment]
> What about making it configurable? Is that a good idea?

Yes.  Adding a PR with `size_to_first_byte` as an added DSL option.  Not sure what the default should be.  32 kB for now.

**Comment by nateberkopec** [comment]
I don't like the idea of closing a bug with a config setting. You shouldn't need to configure Puma to make chunked responses work correctly. Am I reading this wrong?

**Comment by dentarg** [comment]
I don't think you are, and I agree.

Then the buffering should be opt-in? Or removed completely? Or is there another way?

**Comment by dentarg** [comment]
> I suspect a more reliable solution for Sinatra is to switch to the new Streaming body #2740, that wouldn’t be buffered, or? Need to try this myself

I tried this https://github.com/dentarg/testssl.web/commit/5e6b14bb3dd83d0db5044e9d9b560533f500e664 and then streaming works in Puma 6 (this code does not work in Puma 5), not sure everyone should need to make changes like this though?

**Comment by dentarg** [comment]
@ioquatix Sorry to bother you, but would you like to weigh in on this issue?

**Comment by ioquatix** [comment]
As discussed, buffering is critical to the latency/throughput trade offs of an application.

I believe that when streaming, you should not be buffering - it becomes an application concern to decide the throughput and latency trade off.

I model this in Falcon using the concept of `ready?`. If a body is ready, reading from it won't block.

A user stream can have a small internal buffer. If there is a chunk in the buffer, then `ready?` would be true. If the user stream is empty (the application has not generated a chunk, `ready?` is false).

For an `Array` and other enumerable bodies (respond to `to_ary`) we should always consider it to be `ready?`. This is one of the reasons for explicitly modelling enumerable body vs streaming body. If you recall, `Rack:ETag` was not able to distinguish between these two cases and ended up breaking streaming on a fairly regular basis.

At the output layer, you can take advantage of `ready?` to avoid latency issues. For example, if the response body is always ready, we don't need to flush and can let TCP continue the buffering: <https://github.com/socketry/protocol-http1/blob/e6a9235102986a7a5462aea251f2fc9cdc00d65b/lib/protocol/http1/connection.rb#L288>. You can search for other instances of `ready?` in that code to see how the buffering strategy works.

The actual implementation of `ready?` is non-trivial for Rack 2 but fairly straight forward in Rack 3.

For enumerable body: <https://github.com/socketry/protocol-rack/blob/73705f364ba009eb1bbabbad88de1e627cb37c09/lib/protocol/rack/body/enumerable.rb#L50-L53> (now that I look on it, I realise the first check for `Array` is redundant :p).

For streaming body the default is used (from inheritance): <https://github.com/socketry/protocol-http/blob/5f9c3d4fcda5bf89e8e033d8e1ff210f0dc8342d/lib/protocol/http/body/readable.rb#L47-L52> which is `false`.

The implication of this, as outlined above, is that streaming responses will map output chunks to TCP packets, and if the user does a poor job of serialising the output, that's on them (according to the implementation).

If you want to improve the buffering in this case, I'd advise you to check `TCP_NODELAY` and `TCP_CORK`.

**Comment by ioquatix** [comment]
> Additionally, when discussions about Rack middleware were happening, the idea of computing the content length for a 'knowable' body was discussed and seemed like a good idea. Code below. Maybe this should be removed for Array/Enum bodies, and they should just be sent chunked? Added benefit would be that the full body would not need to be accumulated before sending.

My opinion is, you should ignore the content-length in the rack response headers. It's dangerous if incorrect (e.g. buggy code), it can cause security issues <http://projects.webappsec.org/w/page/13246931/HTTP-Response-Splitting>.

Falcon extracts the length and may use it in cases where it makes sense <https://github.com/socketry/protocol-rack/blob/97ec51b0f015a7d2a6b70a283a4d6a34c08d5d0c/lib/protocol/rack/body.rb#L16-L20> but it's not used generally, i.e. it's only used for enumerable bodies: <https://github.com/socketry/protocol-rack/blob/97ec51b0f015a7d2a6b70a283a4d6a34c08d5d0c/lib/protocol/rack/body/enumerable.rb#L20-L27>.

When writing it out (protocol specific) we try to validate the response body length and the specified content-length is correct, and fail if not: <https://github.com/socketry/protocol-http1/blob/e6a9235102986a7a5462aea251f2fc9cdc00d65b/lib/protocol/http1/connection.rb#L283-L285>.

It's less of an issue for HTTP/2 since the binary framing does not depend on the `content-length` header (which serves as more of a hint). That being said, there are some very odd proxy implementations which convert HTTP/1 -> HTTP/2 and completely fail at handling content-length headers. e.g. check <https://portswigger.net/research/http2> specifically "H2.CL Desync on Netflix".

So... my advice is:

- User/application provided content-length should not be trusted and can be a major security issue.
- Generating content length makes total sense to me (e.g. when you know it's an Array, it's cheap).
- You can decide the trade off - falcon accepts user provided content length but validates it at the protocol level, OR
- You can never trust the user provided content-length and recompute it, or drop it completely (allowing you to use chunked encoding).

**Comment by MSP-Greg** [comment]
@ioquatix  Thanks for your responses here and elsewhere.

> Generating content length makes total sense to me (e.g. when you know it's an Array, it's cheap).

That's one thing that's bothered me about the Rack spec -'The Enumerable Body must respond to each. It must only be called once'.  If the body is an Array, why the limitation to only call `each` once?  Or, call `each` to determine content-length, then call `each` to transmit, buffering as desired?  Obviously, both calls would occur before calling `close`.

JFYI, re content-length, I'm only referring to app provided content-length for use in the response.

**Comment by ioquatix** [comment]
> That's one thing that's bothered me about the Rack spec -'The Enumerable Body must respond to each. It must only be called once'. If the body is an Array, why the limitation to only call each once?

The assumption is that the enumerable body can be any kind of object (e.g. a file) and you can't assume it will not be stateful when calling each. However, if you determine that it's an `Array` instance, it would stand to reason that you could call each as many times as you want without side effects (assuming that the user has not sub-classed it and done something funky).

If you are concerned about this (and potentially other) edge cases, there would be nothing wrong with calling `body = body.to_ary`. But I think the `Array` case is so common, and the most easily optimised, that it's obvious. However, I'd be happy to accept a PR to clarify this in the Rack spec.

**Comment by MSP-Greg** [comment]
Just to make sure all are aware, `to_a` and `to_ary` are similar, but different. `Enumerable` has a `to_a` method, `Array` has a `to_ary` method (returns `self`), and also a method `to_a` because `Enumerable` is in its instance chain.

> for a file, it might have internally blocking reads

That, along with the 'text' based iteration was the reason for my [PR](https://github.com/rack/rack/pull/1744) in Rack...

**Comment by ioquatix** [comment]
Thinking about it further, `File#each` in binary mode should probably just yield page sized chunks.

**Comment by MSP-Greg** [comment]
Probably a good idea, but I wonder how many things might break...

Re this issue, I think it would be helpful for an app to define whether an enumerable body (not an Array) requires 'stream' based writing or whether the full enumeration should happen fast enough that buffering can be considered.

**Comment by ioquatix** [comment]
I think the current answer is:

- Enumerable bodies can be buffered but don't need to be.
- Streaming bodies shouldn't be buffered.

**Comment by MSP-Greg** [comment]
As in a streaming body responds to `call`?

**Comment by ioquatix** [comment]
Yes, as per the description in the rack spec (enumerable bodies respond to each, otherwise it's a streaming body and must respond to call).

**Comment by MSP-Greg** [comment]
Thanks.  I thought as much.  But, the issue is whether enumerable bodies that should be streaming bodies exist in the wild.

Or, the issue with the Sinatra file is that it's assuming enum bodies are not buffered, and hence, TTFB should be immediate.  But since it's buffered, it is not...

**Comment by ioquatix** [comment]
> Or, the issue with the Sinatra file is that it's assuming enum bodies are not buffered, and hence, TTFB should be immediate. But since it's buffered, it is not...

Sinatra should not be using enumerable bodies for streaming, or it should have a body that responds to `each` but not `to_ary`. This indicates that you can't buffer it, basically, IMHO, because the presence of `to_ary` indicates there is some way that you can generate a buffered representation of it. That doesn't mean you don't buffer in the network or TCP layer - but if you choose to do that, you are making an explicit throughput/latency trade off and maybe in this case, the application doesn't expect that.

Thinking bigger picture, one thing to be aware of, is web browsers typically buffer 8KiB more or less before they start streaming and/or processing data - unless it's a real time WebSocket or Server Sent Events - browsers deal with that without buffering in my experience, so... what I'm saying is - if you do a little buffering on the network side and server side, in practice it might not be that bad, because clients are probably going to do at least some level of buffering too. In other words, even if you don't buffer anything on the server, the client may still choose to do that, and thus for Sinatra, the result might be the same in practice... unless they are doing WebSockets / SSE / full-duplex fetch / etc.

**Comment by dentarg** [comment]
> the issue is whether enumerable bodies that should be streaming bodies exist in the wild

That would be all of them? :) "streaming bodies" where just now introduced (#2740, https://github.com/rack/rack/pull/1745). Sinatra has been around for 15 years.

Okay, so we have found the bug, using streaming in Sinatra shouldn't be buffered as there's no `to_ary` method at https://github.com/sinatra/sinatra/blob/v3.0.2/lib/sinatra/base.rb#L436-L491 nor in https://github.com/sinatra/sinatra/blob/v3.0.2/sinatra-contrib/lib/sinatra/streaming.rb. 

Yes, I think the point of streaming in Sinatras was to enable SSE: https://github.com/sinatra/sinatra/tree/v3.0.2#streaming-responses

**Comment by MSP-Greg** [comment]
[`text/event-stream`](https://html.spec.whatwg.org/multipage/iana.html#text/event-stream)?  See https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events-intro

**Comment by ioquatix** [comment]
As you've clearly pointed out, there was no mechanism for indicating the buffering strategy that should be used before Rack 3, and thus in general, streaming with Rack was impossible without relying on optional or implementation specific behaviour.

**Comment by jarthod** [comment]
Hello, I just want to give a bit of feedback here. As I tried upgrading to puma 6 I noticed it broke streaming in my Rails app too. I'm using my [render-later](https://github.com/jarthod/render-later) library which uses classic rails controller streaming (+a couple hacks to actually get it to work as it's mostly broken by default). It's easy to reproduce the problem as I wrote a spec already, so running `render-later` specs (`rake`) with puma 6 gives:
```
[render-later] (master) > rake
.......F
Failure:
RenderLater::EngineTest#test_streaming_works [/home/bigbourin/work/render-later/test/render-later/engine_test.rb:33]:
Not enough time between first and last chunk.
Expected 0.00048107299999999853 to be > 1.
```

Though it works fine with puma 5. But,

---

I already had a look at #3004 and tried with this branch (`MSP-Greg:00-size-to-first-byte`) and I can confirm that using this version (`gem 'puma', github: 'MSP-Greg/puma', branch: '00-size-to-first-byte'`), it seems to fix the problem for my use-case :heavy_check_mark:  :
```
[render-later] (master) > rake
..........
Finished in 2.366557s, 4.2255 runs/s, 8.0285 assertions/s.
10 runs, 19 assertions, 0 failures, 0 errors, 0 skips
```

So honestly I did not spend much time investigating the changes and how the MR fixes this, I can wait for `6.0.1` ☺
But as it seems my use-case was not puma 6.0.0 ready, if you need my opinion in some decisions do not hesitate (I can spend more time investigating if needed too).

Thank you all for your work :bow:

**Comment by MSP-Greg** [comment]
@jarthod Thank you for testing PR #3004.

It's an update to #2896, which attempted to determine properties of the response body and adjust how the response body was assembled/transmitted.  That came out of running benchmarks using various body type/size combinations and seeing where Puma's performance might be able to be improved.

#2896 was a bit too aggressive and didn't account for streamed bodies that were enumerations.  #3004 has added more tests and CI jobs, so hopefully it's ready for production...

**Comment by jarthod** [comment]
Ok thanks for the summary! So I shall wait for this to me merged then.

And if I understand correctly, with Rack 3 the prefferred way to stream is now "streaming bodies" (`call`able) instead of enumerable, but as this was just implemented and requires Rack 3 I suppose this won't change before a while in Rails ?

**Comment by ioquatix** [comment]
We will be working on updates to Rails pretty soon.

**Comment by jarthod** [comment]
@ioquatix Ok great, feel free to ping me to test the branch :)
