### ISSUE TITLE
Fails on master

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#3102]
What happened there, I wonder.

**Comment by MSP-Greg** [comment]
Because we've got retry & the timeout wrapping every test, it can be difficult to see problems in the test system.

I shut both off, and have been updating tests in my fork.

Some issues:

1. With threading in the test system, uncaught errors cause 'exception in another thread'.
2. io errors raised vary by platform.
3. There are many `read`'s in the test system, and parallel testing runs in threads.  Hence, blocking.

CI runners (multiple VM's on one system) vary.  I think I've got the test system both faster and more reliable.  I also extracted the client request code shared by some of the files starting a Puma server 'in process' (not the integration tests).

I'm waiting to run it Friday afternoon US, as that time often has busy runners.  For now, I've left retry and timeout intact.  It's a start...
