### ISSUE TITLE
fork_worker auto-forking only works once

### ISSUE THREAD

**Issue by jpr5** [puma/puma#3180]
**Describe the bug**

The automatic "restart workers after N requests" seems to only ever work once.  What is the use in only doing it once?  

As well, the output from the server indicates that only worker 1 gets restarted.  The docs say worker 0 "initializes a new copy of your application first", which is, what, an `exec()`?  If it's a new proc, I'd expect it to show a new PID there, no?

**Puma config:**

`puma.rb`:
```
bind "tcp://0.0.0.0:8080"

workers 2
threads 1,1
fork_worker 10

app do |env|
  [200, {}, ["hello world"]]
end
```

**To Reproduce**

Run: `puma -C puma.rb`
Run: `ab -n 21 -c 1 http://127.0.0.1:8080/`

Then observe a phased restart.

Then subsequently run the `ab` command any number of times and never see another phased restart happen.  

**Expected behavior**

Expect a phased restart every N requests per worker.  

**Desktop (please complete the following information):**
 - OS: macOS 13.4 (Ventura)
 - Puma Version: 6.3.0

**Comment by dentarg** [comment]
Just a quick note that we also have https://github.com/puma/puma/issues/2985

**Comment by willkoehler** [comment]
I was able to reproduce locally using @jpr5's steps and I can see why we only restart once. Here's the code that determines whether to restart:

https://github.com/puma/puma/blob/b2610b3ed75418cd5f7858390f753d9a9f62bd7c/lib/puma/cluster.rb#L293-L300

It calls `fork_worker!` to trigger a `phased_restart` when the first worker has `w.phase=0` and the first worker's request count `w.last_status[:requests_count]` is greater than `@options[:fork_worker]` (the value of fork_worker in the Puma config).

`fork_worker!` increments the worker phase by one.

https://github.com/puma/puma/blob/b2610b3ed75418cd5f7858390f753d9a9f62bd7c/lib/puma/cluster.rb#L278-L283

So after the phased restart, the first worker `w.phase=1` and the first worker `w.last_status[:requests_count]` continues to grow.

Because we only trigger a phased restart when `w.phase=0` we will never trigger another phased restart after calling `fork_worker!`

I am way out my depth here so I don't know where to take this next. I'm not sure if the worker `phase` and `request_count` are supposed to reset after a restart (that was what I expected at first). Or possibly we need to do a modulo check on the `request_count` vs `>=`

**Comment by jpr5** [comment]
I appreciate you all looking into this.  🙏 

I just want to offer one more bit of perspective: what is the use of a single restart?  Perhaps it was done once to prove that it worked, as it's labeled experimental, and then someone forgot to make it repeat?  Auto-restart after N requests is a common concept in app servers; this is the only place I've encountered it where it is limited to working only once.  I cannot see the value of that beyond a PoC, but it works so why not make it a repeating thing?  Plus it violates a common expectation (principle of least surprise); yes there's one mention of it being "once" in the docs, so sure, you can tell me GFYYMMV, but Puma is _awesome_ and this just looks like an oversight..  so I claim it's a bug.

Again, appreciate the consideration.

**Comment by nateberkopec** [comment]
> worker phase and request_count are supposed to reset after a restart (that was what I expected at first)

That seems like an oversight to me, or at least a good way to fix this.

**Comment by johnnyshields** [comment]
>what is the use of a single restart?

@jpr5 the purpose of the single re-fork is to use COW (Copy-on-Write) memory sharing. The reason there is only one re-fork is that after N (e.g. 1000) requests you have populated the bulk of memory of your memory usage (initial app load + things that are autoloaded on requests) hence forking from that "warmed-up" worker will included 80-90% of the stuff you are going to load.

Beyond that, any extra memory consumption by any worker is probably either (a) memory leaks and (b) things that can/will be GC'ed. Hence there are strongly diminished returns on subsequent re-forks; in fact, you may actually be sharing junk memory at that point.

Any implementation of multiple re-forks should come with analysis to show that it is actually beneficial to reduce overall memory consumption. I am skeptical that it would be.

**Comment by nateberkopec** [comment]
Oh man, I was totally turned around on this. @johnnyshields has it right.

In my head I thought `refork` wasn't forking after the initial refork in, for example, the case of a worker dying and needing to be replaced.

But Johnny's explanation is correct. 

We will not support auto-restart after N requests in Puma core (try puma-worker-killer gem or similar for that, it's possible) and that's not what this feature is actually intended for.
