### ISSUE TITLE
ARM JRuby - consistent failures

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#3446]
**Describe the bug**

I thought I'd check if JRuby CI would run on the GitHub Actions arm64 macOS runners.  Consistent failures as below:

GHA job: macos-14 jruby
```text
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 21.0.4+7-LTS on 21.0.4+7-LTS +jit [arm64-darwin]
SyntaxError: /Users/runner/.rubies/jruby-9.4.8.0/bin/jruby:1: invalid multibyte char (UTF-8)
```

GHA job: macos-14 jruby-head
```text
jruby 9.4.9.0-SNAPSHOT (3.1.4) 2024-08-12 52b51d5bb8 OpenJDK 64-Bit Server VM 21.0.4+7-LTS on 21.0.4+7-LTS +jit [arm64-darwin]
SyntaxError: /Users/runner/.rubies/jruby-head/bin/jruby:8: syntax error, unexpected local variable or method
if command -v local >/dev/null; then
              ^~~~~
```

Anyone have any idea what the issue is?  Both tests involve restarting Puma.

**Comment by johnnyshields** [comment]
@headius

**Comment by headius** [comment]
These errors do not seem to be related to aarch64, even though they may only be appearing on that platform.

The two errors you provided are in the JRuby launcher executable. Both appear to be executing as though they are Ruby scripts when they are not.

```
SyntaxError: /Users/runner/.rubies/jruby-9.4.8.0/bin/jruby:1: invalid multibyte char (UTF-8)
```

My guess is that this is actually the native `jruby` executable built by the `jruby-launcher` gem, and for whatever reason it is being interpreted as a Ruby file.

```
SyntaxError: /Users/runner/.rubies/jruby-head/bin/jruby:8: syntax error, unexpected local variable or method
if command -v local >/dev/null; then
              ^~~~~
```

This looks like our sh-based launcher (https://github.com/jruby/jruby/blob/4b0f4fd6a599c2c782845da738b1ab015251edd4/bin/jruby.sh#L22) also being executed as a Ruby script.

I can't see how these jobs were executed so I am unsure why the launchers would have been treated like Ruby code, but that's the real issue here.

**Comment by headius** [comment]
I can reproduce both errors locally by simply pointing a `ruby` command (JRuby or CRuby) at the launcher executable. The first example is using the sh script and the second is using the native launcher.

```
[] jruby $ ruby bin/jruby   
SyntaxError: bin/jruby:8: syntax error, unexpected local variable or method
if command -v local >/dev/null; then
              ^~~~~
[] jruby $ gem install jruby-launcher
Fetching jruby-launcher-1.1.19-java.gem
Building native extensions. This could take a while...
Successfully installed jruby-launcher-1.1.19-java
Parsing documentation for jruby-launcher-1.1.19-java
Installing ri documentation for jruby-launcher-1.1.19-java
Done installing documentation for jruby-launcher after 0 seconds
1 gem installed
[] jruby $ ruby bin/jruby            
SyntaxError: bin/jruby:1: invalid multibyte char (UTF-8)
[] jruby $
```

Perhaps you can provide more context for the CI failures?

**Comment by MSP-Greg** [comment]
Thanks for the response.

> I can't say why it's happening without more context

See https://github.com/MSP-Greg/puma/actions/runs/10373812369.  The macos-14 JRuby jobs fail, and the macos-13 JRuby job passes.  I'll look into it more later.  Maybe there's something different about the runners.

**Comment by headius** [comment]
@MSP-Greg Ok thanks for the job run...

One of the two failures appears to be skipped normally on JRuby. I'm not sure why it is not skipped for the new runs: https://github.com/MSP-Greg/puma/actions/runs/10373812369/job/28720380778#step:8:818

The failures seem to all involve `MinitestRetry` but that library seems pretty simple and not related to the improper launching.

Looking at the `test_plugin` failure, I see the following in the test:

https://github.com/puma/puma/blob/673a9e7e89ab33726f0cc821fa04e46bcb3d61af/test/test_plugin.rb#L11

This `cli_server` function launches a subprocess:

https://github.com/puma/puma/blob/d5800b63ea6a79708b73de2436e3aa06d837030c/test/helpers/integration.rb#L68-L90

The command lines created here use `bundle exec` as shown in the `BASE` constant above:

https://github.com/puma/puma/blob/d5800b63ea6a79708b73de2436e3aa06d837030c/test/helpers/integration.rb#L20-L21

I would guess that the problem is coming from that `bundle exec` not handling the JRuby launcher correctly, and improperly treating it as a Ruby script.

**Comment by headius** [comment]
Correction... the command lines use either `bundle exec` **or** whatever `Gem.ruby` produces, so the latter form could be implicated as well.

**Comment by MSP-Greg** [comment]
Thanks.  I'm working on it, this is interesting.  I changed the base code to be `BASE = "#{Gem.ruby} -Ilib"` since RUBYOPT is set to include `bundler/setup`.

I also logged `Gem.ruby` at the top of the test logging.  It seems correct.

And, both arm64 jobs are still failing, but the others are passing.  I must be missing something...

See https://github.com/MSP-Greg/puma/actions/runs/10424013081

**Comment by headius** [comment]
It reproduces for me locally on MacOS on M1... I'll see what I can see from this end.

**Comment by headius** [comment]
I believe this is a bug in the restart logic. The server is properly initialized during the tests, but when the restart is triggered it's launching a new instance incorrectly.

**Comment by MSP-Greg** [comment]
@headius

First of all, thanks for your help.  I got it to work, and a noticed a file that I don't recall.

See [5fc904b099a7](https://github.com/puma/puma/commit/5fc904b099a7a65591465ee815d27c24cb1b0b52) from the end of 2011, the file is lib/puma/jruby_restart.rb.  A lot's changed in the years since, but I'm JRuby challenged...

Given the age of the file, I removed it, and ran JRuby the same as Windows in the restart logic.  Do you see a need for the special handling of JRuby?

**Comment by headius** [comment]
I just stumbled onto the same file and I'm investigating whether it is necessary anymore. It's doing some argv-munging that's likely causing this issue, but I'm not clear what its purpose was originally.

I'll keep poking around in this file for now. If you stop by Matrix I'm in the office now.

**Comment by headius** [comment]
I believe this workaround file was added to do two things:

* **Actually** do a native chdir to the target directory. In order to avoid interfering with other threads or other code running on the same JVM, JRuby's chdir is usually fake (simulated by a hidden global variable that file-path operations are aware of).
* **Actually** do a native exec to replace the current process. JRuby did not always do a real exec, and still doesn't on some platforms (Windows), but I don't think this should be necessary now.

It seems like the construction of the `execlp` arguments is correct, but I'm certain this is where something is going wrong. Here's output of the `cmd` and `arg` used inside `chdir_exec()`:

```
/Users/headius/work/jruby/bin/jruby
string
/Users/headius/work/jruby/bin/jruby
string
-I
string
/Users/headius/work/puma/lib
string
/Users/headius/work/puma/bin/puma
string
-C
string
/var/folders/h_/tmq357111c18sxbwlyq34mh80000gn/T/config20240816-5766-6dtfp2.rb
string
-b
string
tcp://127.0.0.1:51605
string
--control-url
string
tcp://127.0.0.1:51604
string
--control-token
string
xxyyzz
string
test/rackup/hello.ru
string
```

**Comment by headius** [comment]
Well here's some "good" news: if I pull that `chdir_exec` function out and call it from CRuby, it errors the same way:

```
$ ruby33 chdirexec.rb
SyntaxError: /Users/headius/work/jruby/bin/jruby:8: syntax error, unexpected local variable or method
if command -v local >/dev/null; then
              ^~~~~
```

I don't think this is properly building the command line for `execlp`.

**Comment by headius** [comment]
This could be a bug in how FFI handles varargs on both CRuby and JRuby.

**Comment by MSP-Greg** [comment]
Thanks for looking at this.  Note that our CI ran fine on macos-13, which is Intel x64.  That's what I find odd...

**Comment by headius** [comment]
A minimal patch to get the restart working correctly for now:

```diff
diff --git a/lib/puma/launcher.rb b/lib/puma/launcher.rb
index 9f0a0a49..afd484c7 100644
--- a/lib/puma/launcher.rb
+++ b/lib/puma/launcher.rb
@@ -287,7 +287,9 @@ module Puma
         close_binder_listeners
 
         require_relative 'jruby_restart'
-        JRubyRestart.chdir_exec(@restart_dir, restart_args)
+        argv = restart_args
+        JRubyRestart.chdir(@restart_dir)
+        Kernel.exec(*argv)
       elsif Puma.windows?
         close_binder_listeners
 
```

This continues to use the native `chdir` but then falls back on normal `Kernel.exec` like the other paths.

The fact that it works on x86_64 does concern me, and it indicate a bug in FFI handling varargs calls on MacOS aarch64.

**Comment by MSP-Greg** [comment]
Your patch fixed the issue, both jruby and jruby-head are passing in Actions.

**Comment by headius** [comment]
I still need to follow up with fixes for JRuby + FFI + Apple Silicon but I'm glad the workaround is good for now.

**Comment by headius** [comment]
I have filed ffi/ffi/#1121 for the remaining varargs issue, since I believe it is currently affecting both CRuby and JRuby on MacOS AArch64.

I don't think there's anything else that needs to be done for this issue, right @MSP-Greg?

**Comment by MSP-Greg** [comment]
@headius

Thanks.  Since #3467 was merged, we have been running with macOS-14, which is ARM.  It's been passing.
