### ISSUE TITLE
Option to skip SIGUSR2 handling so we can use Java Flight Recorder

### ISSUE THREAD

**Issue by mohamedhafez** [puma/puma#3567]
Puma [traps SIGUSR2](https://github.com/puma/puma/blob/59c42f6f1d62e1c34b106659d98165600a60f486/lib/puma/launcher.rb#L423) and treats it as a signal to restart itself. However, Java Flight Recorder uses that same signal for its internal functioning. Java Flight Recorder is a very useful, commonly used diagnostic tool in the Java world, and is used by JRuby and TruffleRuby maintainers and end users. Unfortunately we can't use it on Puma processes without making a fork of Puma that disables `SIGUSR2` trapping.

Would you guys accept a pull request where I skipped the setup of `SIGUSR2` handling in [setup_signals](https://github.com/puma/puma/blob/59c42f6f1d62e1c34b106659d98165600a60f486/lib/puma/launcher.rb#L422) if the environment variable `SKIP_SIGUSR2_HANDLING` was present?

**Comment by headius** [comment]
@nateberkopec The problem here is that on any JVM-based Ruby, it's not possible to profile an application running in Puma *at all* because the hardcoded USR2 interacts badly with the JDK Flight Recorder profiler's use of USR2.

There are other places where the signal set-up is different for JRuby, such as for INFO: https://github.com/puma/puma/blob/da6ca9744183c92e2433a54672a904d349d6b485/lib/puma/launcher.rb#L472

What I think we want here is simply to be able to configure the signals used for these features, and to turn them off if not needed or if they interfere with something else.

**Comment by dentarg** [comment]
Sounds like this makes sense.

**Comment by nateberkopec** [comment]
OK, we'll accept a PR for it 👍
