### ISSUE TITLE
Ruby 2.1: Out-of-Band GC

### ISSUE THREAD

**Issue by thehappycoder** [puma/puma#450]
http://tmm1.net/ruby21-oobgc/?utm_source=rubyweekly&utm_medium=email

Is it possible to do with puma?

**Comment by wjessop** [comment]
I'd be really interested in Puma OOB GC functionality. Much as I like threads I really don't see much shift towards thread safety in a lot of Ruby gems which makes most larger apps with dependencies pretty much only safe to run single threaded, so a non-threaded only implementation would still be helpful.

**Comment by schneems** [comment]
> Much as I like threads I really don't see much shift towards thread safety in a lot of Ruby gems

Between puma and sidekiq and passenger almost any mainstream gem out there is threadsafe.

Not sure if you saw but GitHub actually turned off their OOBGC and got something a 10% decrease in overall CPU utilization. While GC pauses might add some time to a request it is likely minuscule between incremental GC, lazy sweep, and generational GC an individual GC run shouldn't be taking a significant portion of a request.

If you're really gung-ho about adding OOBGC support let me know what kind of hooks Puma could introduce to allow you to build it as a third party gem.

**Comment by wjessop** [comment]
I have no doubt that Puma, Sidekiq etc. are threadsafe, it's going to be a really basic Rails app that relies on just the big names though.

The app I'm working on right now has 374 dependencies (direct and indirect). A relatively small personal project has 112. I picked the first five dependencies at random of that larger project (that wasn't a Rails or a Rails dep, or a test dep) and checked the repos for mention of thread safety. They don't mention it.

I suspect (and I'd be interested to see real stats rather than my gut feelings) that most non-trivial applications will depend on a fairly large number of gems, very few of which will be either written with thread-safety in mind, or will have the thread-safety documented.

> Not sure if you saw but GitHub actually turned off their OOBGC and got something a 10% decrease in overall CPU utilization.

I did see that just today, it was very interesting. The biggest thing I'm interested in there was the 25% reduction in response times. If that's really the case then it's a pretty big reason not to implement OOB GC, but I think I'd like more information, for instance, were they queueing requests behind the GC in a process rather than routing requests round it?

In terms of CPU though, we already trade CPU for user experience with when we gzip responses. There's a tradeoff there, and it's something we need to balance, but we're currently averaging about 14ms GC time in our responses (Ruby 2.3.4, yes we need to upgrade) so we'd be willing to trade at least some CPU time to drop that figure.

I got @ketan's middleware working and I'll do some testing to see what the tradeoffs are in our environment and I'll try to report back.

Thanks for the response!

**Comment by schneems** [comment]
I wasn’t saying that puma and sidekiq are threadsafe but rather apps that use puma and sidekiq in production are threadsafe. The dependencies that those apps use are either already threadsafe or have been found to have threading bugs in them and then been fixed.

If you don’t want to use threads with puma I would recommend using unicorn which will give you better performance as long as it is running behind nginx then you’re protected from slow clients. As a bonus then you can use the already written OOBGC.

**Comment by wjordan** [comment]
I've added PR #1648 that implements an `out_of_band` hook that can be used for implementing out-of-band GC in Puma.

OOBGC still provides my own production workload ~10% faster response times on Ruby 2.5 (see https://github.com/tmm1/gctools/issues/16#issuecomment-390381824 for some details/discussion). Whether OOBGC ends up being useful or not will depend a lot on workload, exact tuning of GC variables, and also the exact OOBGC algorithm used.
