### ISSUE TITLE
Puma inconsistently creating PID file

### ISSUE THREAD

**Issue by davejlong** [puma/puma#466]
I have a Rails app using MRI 2.0.0-p353 and it's own RVM Gemset named "dashboard". I've done the following to setup my app with Puma:

Create RVM Wrapper

```
rvm alias create dashboard ruby-2.0.0-p353@dashboard
rvm wrapper dashboard puma
```

Created a Config file in `{Rails Root}/config/puma.rb`

```
threads 1, 6
workers 2

preload_app!

cwd = File.dirname(__FILE__) + '/..'

directory cwd
rackup "#{cwd}/config.ru"

pidfile "#{cwd}/tmp/pids/puma.pid"

bind 'tcp://0.0.0.0:9292'
bind "unix://#{cwd}/tmp/sockets/puma.sock"

on_worker_boot do
    ActiveSupport.on_load(:active_record) do
        ActiveRecord::Base.establish_connection
    end
end
```

When I run `/usr/local/rvm/wrappers/dashboard/puma --daemon -C /data/deploy/dashboard/config/puma.rb`, I only get a PID file generated sometimes. Sometimes, if I lookup the PID of the application (`ps aux | grep dashboard/puma`), and send the `SIGUSR1` signal to it, I'll get a PID file generated, but not always.

The behavior is very inconsistent and there will be no PID file ~2/3 of the time.

**Comment by JonasBorchelt** [comment]
I have the same problem with version 2.14.0: get no pid if I start the server daemonized.

**Comment by mdesantis** [comment]
Same problem here

**Comment by kreynolds** [comment]
Same here, Centos 7, ruby 2.3.3, puma 3.6.2, with or without --daemon, all specified via the command line, no config file. No state file either, not sure if there should be one.

```
puma config.ru -t 0:4 --pidfile /home/user/puma.pid -S /home/user/puma.state
```

**Comment by jbarwick** [comment]
Is this still an active issue as of May 2017?
Ok, I'm on Puma 3.9.1.  My issue is not that the PID file is missing.  it's there.

My Issue is that the PID file is written AFTER daemonization!!!

That means, there is no PID file after the process forks.  The PID file is only written AFTER puma.rb executes fully (it seams) after all workers threads have been started (min-threads).

If you are using ActiveRecord, and it attempts to connect to the database, or have many workers/threads, this can take a few hundred milliseconds.

If you are using a 'forking' configuration in your capistrano, init.d, upstart, or systemd scripts, then after puma daemonizes, the PID file will either not be there (until later) or will contain an old process ID (cuz the new one hasn't been written yet).

The best way to get around this is to use a non-forking configuration (e.g. don't rely on the PID file at all..don't...it's ok...don't worry about it...it will get written soon enough).

I use both upstart and systemd

I also use .rbenv

In upstart and system.d I have

respawn
chdir /myhome/myapp
env RAILS_ENV=production
exec /myhome/.rbenv/shims/bundle exec puma config.ru
 
Type=simple
Restart=always
WorkingDirectory=/myapp
Environment=RAILS_ENV=production
ExecStart=/myhome/.rbenv/shims/bundle exec puma config.ru

And because puma is not running in daemon mode, the upstart and systemd will feel that the process is indeed 'started'.  

If you want to terminate puma, either Ctl-C the process (kill the upstart/systemd service thread) or call:  "pumactl -S statefile.state stop"

**Comment by feliperoveran** [comment]
@jbarwick Writing the pidfile after daemonization is the desired behavior, since the `pid` will be different after daemonizing.

Explanation:
When daemonizing we need to make sure two things never happen - `defunct processes` and `that our process never has a controlling terminal`.
To do so, we `fork` twice (calling `setsid` between both forks, along with setting the `creation mask` and unlinking `stdin`, `stdout` and `stderr` file descriptors). On the first time we make sure the `ppid - parent pid` is the `init` process and that child processes will always be wait'ed on (thus not creating defunct processes) while on the second time, we make sure our process is not a `session leader`, so it can't be assigned with a controlling terminal.

After Ruby 1.9, which introduced `Process.daemon`, we no longer need to do the `fork - setsid - fork` process by hand since Ruby handles that for us.

Digging a little deeper into Ruby's implementation of `Process.daemon`, you can see the mentioned double-forking behavior [here](https://github.com/ruby/ruby/blob/56451d5966b2bc276ac4b677a96e2c137cf0248f/process.c#L6023) and the spec testing that the `PID` will be different after daemonizing [here](https://github.com/ruby/ruby/blob/1d15d5f08032acf1b7bceacbb450d617ff6e0931/spec/ruby/core/process/daemon_spec.rb#L55).

Taking a closer look to Puma's startup process, we can see [here](https://github.com/puma/puma/blob/5a6f3f2b34f51b8b017fd71b550d9287caf630ae/lib/puma/single.rb#L83) that it is calling `Process.daemon`, thus we will have a different `PID` after daemonizing. So, if we wrote the pidfile before such process, we would have a wrong `PID` being written to the file.

For more information about the `double-forking`, `setsid` and everything related to the daemozination process, check `Stevens's Advanced Programming in the UNIX Environment - chapter 13`

**Comment by jbarwick** [comment]
I understand your response.

However, it would be nice if the parent process waited for the deamon process to write its pie file before it terminated.

I doesn’t feel right to put “ExecStart=/bin/bash -c “puma -d;sleep 2” in my systemd script

**Comment by augustosamame** [comment]
I have just setup Puma with systemd on Ubuntu 18.04. I also get this when running `sudo systemctl status puma.service`

```
Apr 28 21:06:37 ip-172-31-55-37 systemd[1]: Starting Puma HTTP Forking Server...
Apr 28 21:06:37 ip-172-31-55-37 rvm[7959]: Puma starting in single mode...
Apr 28 21:06:37 ip-172-31-55-37 rvm[7959]: * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
Apr 28 21:06:37 ip-172-31-55-37 rvm[7959]: * Min threads: 0, max threads: 8
Apr 28 21:06:37 ip-172-31-55-37 rvm[7959]: * Environment: production
Apr 28 21:06:37 ip-172-31-55-37 rvm[7959]: * Daemonizing...
Apr 28 21:06:37 ip-172-31-55-37 systemd[1]: puma.service: Can't open PID file /home/deploy/rails_app/shared/tmp/pids/puma.pid (yet?) after start: No such file or directory
Apr 28 21:06:38 ip-172-31-55-37 systemd[1]: Started Puma HTTP Forking Server.
```

But everything seems to work fine. Puma starts properly on server reboot and I can start/stop/restart using the systemctl commands. Why would I need to put the `sleep 2` in the systemd script to wait for the PID?
