### ISSUE TITLE
Should Puma handle Expect: 100 Continue?

### ISSUE THREAD

**Issue by tmornini** [puma/puma#519]
As specified in 8.2.3 of the HTTP 1.1 specification: http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html

I found this fascinating:

celluloid/reel/issues#111

counterpoint:

http://www.fallingcanbedeadly.com/posts/http-100-continue-latency-and-you/

**Comment by MichaelSp** [comment]
By the way: unicorn has an implementation for this https://github.com/defunkt/unicorn/blob/ec8c095b9f6081ec1462db6c4392ab181bd6790e/lib/unicorn/http_server.rb#L567-586

**Comment by evanphx** [comment]
Puma now answers immediately that if it detects an `Expect: 100-continue`. The reason it does this rather than taking the unicorn approach to letting the app handle it is that it's extremely unlikely that an app will know how to handle it and clients might send it to any app, even if they don't handle it. Thusly sending `100 Continue` without consulting the app is totally safe.

Future work includes deferring sending the `100 Continue` until the app begins reading the request body (this is how Go handles this).

**Comment by tmornini** [comment]
Nice!
