### ISSUE TITLE
After upgrading to Puma 2.12.0, uninitialized constant Rack::File

### ISSUE THREAD

**Issue by joeyfreund** [puma/puma#732]
After upgrading (from 2.11.3) to 2.12.0, I got the following error:

```
/usr/local/bundle/gems/rack-1.6.4/lib/rack/static.rb:94:in `initialize'! Unable to load application: NameError: uninitialized constant Rack::File
```

Our `config.ru` file is:

```
require 'rack/cors'
require 'rack/static'
require 'sprockets'
require 'coffee-script' # Explicit requrie, to load coffee in a thread-safe way...
require 'sass' # Explicit requrie, to load sass in a thread-safe way...

use Rack::Cors do
  allow do
    origins '*'
    resource '*', :headers => :any, :methods => [:get, :options]
  end
end

map '/assets' do
  environment = Sprockets::Environment.new
  environment.append_path 'assets/javascripts'
  environment.append_path 'assets/templates'
  environment.append_path "#{Gem.loaded_specs['xnjs'].full_gem_path}/lib"
  environment.append_path 'assets/images'
  environment.append_path 'assets/fonts'
  run environment
end

use Rack::Static, :urls => ["/application.css", "/xn.js"], :root => 'public'
run lambda { |env|
  [ 200,
    { 'Content-Type'  => 'text/html',
      'Cache-Control' => 'public, max-age=0' },
    File.open('public/index.html', File::RDONLY) ]
}
```

**Comment by pangloss** [comment]
+1

**Comment by evanphx** [comment]
That's sort of a bug in `rack/static` for not importing the files it needs. Because Puma no longer requires `rack` if the `Rack` constant is missing, it can't see this error.

I'm sorry about his breaking change, I considered bumping puma to `3.0.0` to signal this change.

If this is a deal breaker for you to change your `config.ru` to require `rack`, I can add some work arounds. But the right fix is for you to do `require "rack"; require "rack/file"` to deal with the bug in `rack/static`.

Please let me know what you decide to do.

**Comment by evanphx** [comment]
I've filed a PR against rack to fix the issue there: https://github.com/rack/rack/pull/911

**Comment by pangloss** [comment]
Thanks, that's all I needed to know!

**Comment by joeyfreund** [comment]
Thanks @evanphx, we'll probably wait for your PR to be merged and released.

**Comment by evanphx** [comment]
Closing this since it's `rack` issue now.

**Comment by rayning0** [comment]
Thanks @evanphx! I just had this same problem in my Rails app. Just changed my web server to Puma. Got 'Unable to load application: NameError: uninitialized constant Rack::Cors'. Fixed it by adding:

```
require 'rack'
require 'rack/cors'
```
to config.ru.
