### ISSUE TITLE
Bad configuration advice in Readme? Please clarify.

### ISSUE THREAD

**Issue by robomc** [puma/puma#842]
The threads/workers configuration advice in the Readme conflicts with the advice from Heroku. The Heroku explanation makes more intuitive sense to me. Which is correct?

Readme on worker number:

> On a ruby implementation that offers native threads, you should tune [the number of workers] to match the number of cores available. 

[Heroku on worker number](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#workers):

> Each worker process used consumes additional memory. This limits how many processes you can run in a single dyno

> Loosely speaking, workers consume more RAM and threads consume more CPU, and both provide more concurrency.

Heroku seems to suggest you should run as many workers as your RAM allows for, while Puma's Readme suggests tying these to core count. On a pretty typical VPS instance, this can mean the difference between 4 workers and around *30*.

Since there is completely different advice for this key parameter, from two credible sources, it would be good to double check that the Readme is correct. If it is, I'll see if I can get Heroku to update their guide.

**Comment by Edwardzyc** [comment]
Number of workers should equal number of cores if RAM allows for it. 

Does that make more sense? (At least on MRI)

**Comment by robomc** [comment]
What if there is 32GB of RAM and 2 cores though. 

Heroku's advice suggests you should keep adding workers until you run out of RAM. Is that not the case? Should you stay at just two workers in that situation?

**Comment by evanphx** [comment]
I prefer my advise to Heroku's in this case. That's because adding more workers only increases scheduler contention within the kernel. If you have the same number of workers as cores and are using a decent number of threads, then you'll get maximum throughput out of the machine.

**Comment by nateberkopec** [comment]
For Heroku specifically, there's another concern.

Heroku's routing layer is "dumb" - that is, it randomly selects dynos to route your requests to. Puma's routing is a little more "smart", because it's basically routing requests to a "free", non-busy Puma worker when possible.

I've seen huge response queueing improvements on Heroku when reducing the number of dynos and increasing the number of workers-per-dyno. For example, moving from 30 1x dynos with 2 workers each to a single Perf-L dyno with ~20-30 workers will usually greatly improve response queueing and result in fewer timeouts.

Technically I think Performance dynos on Heroku have 8 cores, the normal ones have 4. But again, due to routing, I've seen improvements at even 2-3x the core count.
