### ISSUE TITLE
Puma process doesn't run when using .sock file

### ISSUE THREAD

**Issue by JerryGreen** [puma/puma#862]
I am using rails and trying to start puma server on my production server:

```
user@Ubuntu-1510-wily-64-minimal:~/app/current$ puma -e production -b unix:///home/user/app/shared/tmp/sockets/puma.sock
[9850] Puma starting in cluster mode...
[9850] * Version 2.15.3 (ruby 2.2.1-p85), codename: Autumn Arbor Airbrush
[9850] * Min threads: 0, max threads: 16
[9850] * Environment: production
[9850] * Process workers: 2
[9850] * Phased restart available
[9850] * Listening on unix:///home/user/app/shared/tmp/sockets/puma.sock
[9850] * Daemonizing...
```

No error. Fine. Is that mean puma server is running? Nope.

I try:

```
user@Ubuntu-1510-wily-64-minimal:~/app/current$ kill -9 9850
bash: kill: (9850) - No such process
```

Ok. Maybe it is not the pid? Let's try:

```
user@Ubuntu-1510-wily-64-minimal:~/app/current$ ps aux | grep ruby
ascii-r+  9887  0.0  0.2   9496  2240 pts/0    S+   22:07   0:00 grep --color=auto ruby
```

What is going on? Why I can't start puma server?

NOTE: I successfully did it without `.sock` file (using `RAILS_ENV=production bundle exec rails s Puma -d`)

**Comment by evanphx** [comment]
Remove daemonizing and Puma will tell you the issue.

**Comment by JerryGreen** [comment]
@evanphx Silly me, thank you! I solved it. The problem was there was no stdout and stderr files.

**Comment by pnomolos** [comment]
@evanphx I realize that I'm necroing/hijacking this thread, but is there any reason that Puma doesn't bail and spew an error from the main runner on what could be considered fatal errors?  Items such as "unable to create pid file", "unable to create socket file".  I rarely set up new puma apps so I'm bit by those every time (because I forget what the problem was last time it happened) and burn time trying to figure out what's going on.
