### ISSUE TITLE
Is there a way to kill a Puma worker if client connection got closed?

### ISSUE THREAD

**Issue by yukas** [puma/puma#867]
In our app we have a heavy action which takes time and lots of memory. User can hit reload thus close the connection, but puma worker will continue to crunch data and eat memory. Is there a way to prevent this, maybe by killing a worker. We can't timeout the request. Puma sits behind the Nginx proxy.

**Comment by evanphx** [comment]
No, there is no way to do this. That's not a limitation of puma, it's of all web servers. Even if you looked at the socket directly, it's going to sit in TCP wait state and not indicate that it's closed.

**Comment by stereobooster** [comment]
> No, there is no way to do this

It depends on situation. If server already started processing request and client disconnected you can't do anything about it. But if request was in the que and client disconnected before server started to process response it is possible to detect this situation. Unicorn have this feature: [check_client_connection](https://bogomips.org/unicorn-public/?q=s:check_client_connection&d:..20170324&x=t). What they do is they use [`TCP_INFO`](https://bogomips.org/raindrops/) in Linux/FreeBSD/OpenBSD or try to write partial header before starting worker (and get io error if connection closed). [Original idea proposed by Shopify](https://shopifyengineering.myshopify.com/blogs/engineering/17489012-what-does-your-webserver-do-when-a-user-hits-refresh). Also worth to note that detection only works for TCP loopback or unix socket, which is ok, because everybody use it behind nginx.
