### ISSUE TITLE
Puma hangs with min-threads=0 and queue_requests=false

### ISSUE THREAD

**Issue by osheroff** [puma/puma#876]
With a config of:

```
threads 0,1
queue_requests false
```

I found that Puma would stop responding after some time.  
We managed to get a stack trace out of the hung workers and found a nasty combination:

- The main server thread was stuck down in `ThreadPool#wait_until_not_full`
- The thread pool worker didn't have a worker thread alive

Presumably there's a race condition somewhere between trimming threads and `wait_until_not_full`; bumping our min-threads to 1 seems to have vanished the problem.

**Comment by evanphx** [comment]
What version of puma? There was some fixes related to the threads in the Pool dying prematurely that were fixed.

**Comment by osheroff** [comment]
I'm running with the gemfile pointed at dbb1932

**Comment by evanphx** [comment]
Could you try 2.16.0 and see if it still happens?

**Comment by dadah89** [comment]
I was able to reproduce (somewhat) consistently with 2.16.0. It happens when `trim` is executed at a bad time. In thread_pool.rb, with at least one thread waiting to pick up work and the todo queue being empty, this is what I see:

* a call to `<<` comes
* next `wait_until_not_full` is executed (and it starts waiting on `@not_full`)
* `trim` is executed (because `@waiting` is still > 0, `@trim_requested` gets incremented)
* finally, the work thread wake up, decrements `@waiting`, execute the work (removing the last item from `@todo`), finishes it, an then hits the `@trim_requested`, exiting the loop before executing signaling `@not_full`, so `wait_until_not_full` never exits

In a configuration like `threads 0,1`, that means the worker not accepting more requests.

With more threads (any combination where min and max are not equal), I've seen some weird behavior where when the bug happened, some requests would keep waiting, and when I sent a new request, all of them would get responses at once. Still not sure what happens here (doesn't make much sense looking at thread_pool.rb), would need to debug more.

My test is pretty simple, I send between 1000 and 3000 requests (helps with slower requests, but even with a simple '{status:ok}' response I could reproduce), with the same configuration @osheroff described above, and adding some output when `<<`, `wait_until_not_full` and `trim` get executed. I should try building a test script or maybe a failing test... but hope this info helps.

**Comment by osheroff** [comment]
so should we do something like `not_full.signal` after the worker exits?

**Comment by codehotter** [comment]
Out of curiosity, why are you running with queue_requests = false?

**Comment by osheroff** [comment]
our configuration is (load balancer -> local nginx -> puma), 20 workers and a single thread per worker.  Our workload consists of quite a lot of very short requests and a few very very long requests (1-20 seconds.)  My understanding is that if we run with `queue_requests = true`, a worker that's busy processing a 20 second request maybe `accept()` a smaller request and then get blocked waiting for it to finish

**Comment by laneatomic** [comment]
We are seeing this issue (or one extremely similar) as well. The socket stops responding after an indeterminate number of connections or amount of time. The only way we have found to mitigate is to restart the puma daemon processes. We have `threads 2,6`, `workers 8`, and are binding to a socket. We started seeing this issue after upgrading to Ruby 2.3.0 from Ruby 2.2.3 and Puma from 2.15.3 to 2.16.0. I hope this helps for reproduction.
