### ISSUE TITLE
Puma Streaming/Keep-Open Support

### ISSUE THREAD

**Issue by HoneyryderChuck** [puma/puma#895]
Coming from here: https://github.com/sinatra/sinatra/issues/1035:

I don't know whether I should deem this a Puma or Sinatra issue. Sinatra does seem to lack proper rack.hijack API support. However, I've been trying to add support using it, and it has been getting on my nerves. Time to share my frustration. :) 

The way, I see it, puma does provide support out of the box for io hijacking. Providing SSE support would just be a matter of writing the proper headers, flush them, and **not** close the Puma::Client. And this is what it seems to happen all the time that I don't hijack the socket (`env['rack.hijack'].call`). However, doing that will bypass writing the headers, which means, I have to write them myself (?). Then there's the response_hijack part, which apparently can be also setup.

This has been my quest:

``` ruby
# all sinatra
get '/' do
  # option 1
  # sinatra API, just plain doesn't work with puma
  stream(:keep_open) do |out|
    .....
  end

  # option 2
  # writes headers, closes Puma::Client, socket is gone, no long-lived connection
  response.headers["rack.hijack"] = ->(out) do     
    out.write "Transfer-Encoding: chunked\r\n"     
    out.write "X-Content-Type-Options: nosniff\r\n"
    out.write "\r\n"                               
  end                                              

  # option 3
  # keeps the connection alive, but messes up the headers (status is not flushed anymore, only those headers over there are shown), SSE doesn't work without proper headers
  out = env['rack.hijack'].call                  
  out.write "Transfer-Encoding: chunked\r\n"     
  out.write "X-Content-Type-Options: nosniff\r\n"
  out.write "\r\n"                               
end
```

So, I'm in a conundrum right here. It seems logical that puma has support for this, I just can't find proper examples in the WWGoogle and can't make the API work to my advantage. @evanphx care to provide a raw puma implementation in the examples/ folder? Maybe you have bumped into this already.

**Comment by TiagoCardoso1983** [comment]
I tend to think of this more of a puma "issue" rather than Sinatra. Even if I do this properly and apply a loop inside the stream helper call while writing to the socket (a valid solution advertized by ActionController::Live, for example), I still starve a thread meanwhile, which means, if I have 16 max threads and 16 clients connecting, I don't have enough more threads to continue serving requests. Is that right? If so, is this by design? If not, are there known workarounds? Apparently actioncable worked around it, right?

**Comment by TiagoCardoso1983** [comment]
@evanphx 

https://gist.github.com/TiagoCardoso1983/591d48cfde04219f801fa7fd7966571c

in order to "libify" this, whose concern is to abstract the SSE/Websocket part, sinatra's or puma? from my understanding, sinatra "stream" helper should support the rack socket hijacking API and pass it to an appropriate driver, right?

**Comment by evanphx** [comment]
If you use hijack, you have to write back the whole response on your own. Hijack basically tells puma to do nothing with the socket because the assumption is that the handler has already done everything with it by the time puma sees it again.

I have no clue about sinatra's support honestly, maybe @rkh can shed some light on it?

**Comment by TiagoCardoso1983** [comment]
@evanphx Did you try my example? It actually does this using the reel helpers, with the benefit that the socket is held inside the celluloid io reactor (non-blocking event loop), thereby releasing the puma worker for further http work. 

Sinatra helpers seem to be more focused in eventmachine (I haven't managed to make anything work without it). My question was more if puma should provide some helpers for this use case, as most of the examples around for SSE or long-polling block the puma workers, and this usually ends up bringing performance down or even DoS.

**Comment by evanphx** [comment]
3.4.0, out now, has `force_shutdown_after` which will kill the threads after a specified time. You can use that mechanism to have puma terminate any SSE/long-poll threads.

**Comment by TiagoCardoso1983** [comment]
not my use-case. As I'm hijacking the socket, puma thread is being anyways freed, and a separate thread/event-loop is handling the SSE, I handle termination there. I don't think that a threaded server is a good solution for such long-lived connections such as SSE or websockets, for that matter. But thx for the info.

**Comment by TiagoCardoso1983** [comment]
@evanphx , can we come back at this issue? I've seen you opened a PR to add nio4r, and this could be the solution to the problem. 

A short summary of what was discussed: puma allows support for chunked responses, but not streamed (SSE), although it could. Problem being, the current reactor is read-only, while the writes are performed on the thread pool workers. For proper streaming to be implemented, the reactor must handle reads and writes. Which will probably be handled, as there's a websocket-related PR. 

After the reactor is handled, Puma could allow other types of responses, which implement a well-defined API(?), and this could be better handled [here](https://github.com/puma/puma/blob/46416cb49ed2f16614f019cee969bb8f5d0a6146/lib/puma/server.rb#L693-L699).

I really think that, if puma goes the way of supporting websockets, it could definitely support streaming and chunked responses in a more evented way.
