### ISSUE TITLE
Puma silently exits after "Daemonizing..." from systemd script

### ISSUE THREAD

**Issue by confiks** [puma/puma#941]
I'm having a hard time getting Puma to reliably startup from a systemd script; it simply exits without printing a lot of debug information. The issue is extremely hard to reproduce, and this ticket is more about asking how I could debug the issue further, than to ask you what's wrong.

I deploy my application on AWS, by provisioning a Debian Jessie base image with (among other thing) nginx, Rails, Puma and a systemd startup script, then saving that AMI, and then launching the AMI within an autoscaling group. The problem is that Puma only silently dies when first being launched. Subsequent reboots will launch Puma fine, and launching puma manually (service mypumasystemdname start) will work too.

I use this systemd script:

    [Unit]
    Description=Puma server for app
    After=network.target cloud-final.service

    [Service]
    WorkingDirectory=/var/www/app/current
    User=application
    PIDFile=/var/www/app/shared/puma/pid
    ExecStart=/usr/bin/env bundle exec pumactl -F puma.rb start
    ExecReload=/usr/bin/env bundle exec pumactl -F puma.rb restart

    [Install]
    WantedBy=multi-user.target

With this puma.rb configuration file:

    #!/usr/bin/env puma

    environment 'production'
    daemonize true
    workers 2
    debug

    directory "/var/www/app/current"

    pidfile "/var/www/app/shared/puma/pid"
    state_path "/var/www/app/shared/puma/state"
    bind "unix:///var/www/app/shared/puma/sock"

    stdout_redirect 'log/puma_stdout', 'log/puma_stderr', true

When the system has started up, the Puma startup appears in syslog. The systemctl utility neatly summarizes everything about the startup, including the exit (with status 0):

    admin@myhost:~$ sudo systemctl status puma_app.service
    ● puma_app.service - Puma server for app
       Loaded: loaded (/etc/systemd/system/puma_app.service; enabled)
       Active: inactive (dead) since Fri 2016-04-01 14:09:44 UTC; 2min 50s ago
      Process: 420 ExecStart=/usr/bin/env bundle exec pumactl -F puma.rb start (code=exited, status=0/SUCCESS)
     Main PID: 420 (code=exited, status=0/SUCCESS)

    Apr 01 14:09:40 myhost systemd[1]: Started Puma server for app.
    Apr 01 14:09:44 myhost env[420]: [420] Puma starting in cluster mode...
    Apr 01 14:09:44 myhost env[420]: [420] * Version 3.2.0 (ruby 2.2.4-p230), codename: Spring Is A Heliocentric Viewpoint
    Apr 01 14:09:44 myhost env[420]: [420] * Min threads: 0, max threads: 16
    Apr 01 14:09:44 myhost env[420]: [420] * Environment: production
    Apr 01 14:09:44 myhost env[420]: [420] * Process workers: 2
    Apr 01 14:09:44 myhost env[420]: [420] * Phased restart available
    Apr 01 14:09:44 myhost env[420]: [420] * Listening on unix:///var/www/app/shared/puma/sock
    Apr 01 14:09:44 myhost env[420]: [420] * Daemonizing...

In the (redirected) stdout and stderr files, there is not much to be found:

    admin@myhost:~$ cat /var/www/app/current/log/*
    === puma startup: 2016-04-01 14:09:44 +0000 ===
    [430] Early termination of worker

After this, there are no running puma processes left. When I execute `sudo service puma_app start` manually, Puma perfectly starts up, runs the app and stays running (with an uptime of a few days now).

I've been debugging this issue for three days in a row now, adjusting various parameters and doing a lot of redeploys, but I still don't know what the problem is. The main problem is that I'm not getting more debug information out of Puma (even with the debug config parameter), to the point that the main process even exists with status 0. It might also be worth noting that the output to systemd is not in the puma log files, but this might be intended behavior.

Would anyone know how I could debug this more?

**Comment by dekellum** [comment]
You probably don't want to daemonize puma when using with systemd, or if you do, you'll need to inform systemd that its a forking server.  Check out sample config now on master at docs/systemd.md

**Comment by confiks** [comment]
Alright, it was totally not obvious to me that Puma shouldn't be daemonized when running as, err, daemon from systemd. Especially since it only fails to work in the specific circumstances I described above, and just works otherwise. Thanks for the systemd example script too!

**Comment by jbarwick** [comment]
@dekellum is on the right track.  IMHO, there are challenges with the daemon mode:

We'll make puma start as a daemon.  And below PID is the process ID
The daemon startup process is this:

#puma -d 
process1 -> puma startup PID 1
process2 -> daemon process PID 2 
worker1 -> puma PID 3
worker2 -> puma PID 4
Puma PID 2 outputs the file puma.pid
Puma PID 1 exits (leaves the daemon PID 2 running)

Problem 1:  The PID file is written only after all workers startup.   And this can take a while.
Problem 2:  The process PID 1 exists immediately after it starts the daemon process 

result:  PID 1 would be the 'child process' of systemd.  It exists.  So, systemd would assume the process has exited and stopped.  It doesn't know that PID2 is the 'real' process. 
You can add ExecStartPre= to delete any old pid file and ExecStartPost= to wait for the PID file to be written.  And set the PIDfile= parameter.  But systemd will complain:  "The monitored process is not the child process.  You will probably not know when it exits."  It takes about 3 seconds to start all the workers.  So, adding the ExecStartPost to wait for the pid file will delay your startup.

Well, it works anyway.  So, you could, theoretically, change the systemd service type to 'forking' and use the -d parameter.  But, beware, there is another problem.

Problem 3:  phased-restart

you can do a pumactl -P pidfile.pid phased-restart and the documentation says it will drain the workers before it restarts each one.  Nice.  But, if you use daemon -d mode, there is a problem.
The problem is that if you use daemon mode, and do a phased-restart, the daemon restarts.  This will delete the pid file.  Systemd will assume the process has crashed, and restart the service.

If you do not use daemon mode and issue a phased-restart, the parent process does not exit and the workers restart and get new PIDs.  The parent process keeps its pid cuz it doesn't restart.  NICE. This is the way it should be.

I have communicated to the author of puma (ticket in Github) regarding the issue of the Pid file write timing (i was trying to use daemon mode in systemd). But, I don't think he understood what I was asking.  Anyway, he closed the case.  And this was before I knew about the behaviour of phased-restart.

Moral of the story:

As of Version 3.10.0 (ruby 2.4.1-p111), codename: Russell's Teapot, do not ever ever ever...I mean never use -d daemon mode.  Whether you use systemd or not.  Use some other daemonizer.

So, in sytsemd..use simple mode.  It might seem weird when your program theoretically supports a daemon mode, but it works quite well.  I have tested start/stop/reload/restart and the phased-restart works nicely.  In simple mode running puma interactively without the -d flag.
